/* Biology learning library, revision 2. Original explanations and practice.
   Stable umbrella-topic IDs preserve Build 4/5 mastery. */
const BIOLOGY_UNITS = {
 'Cell Biology': {
  sections: [
   ['Inside a cell','The nucleus contains DNA, which carries instructions for making proteins. Ribosomes assemble proteins. Many chemical reactions happen in the cytoplasm; mitochondria are the main site of aerobic respiration. The cell membrane controls movement into and out of the cell. Plant cells also have a cellulose wall, a permanent vacuole containing cell sap and, in photosynthetic tissues, chloroplasts.'],
   ['Bacteria and specialised cells','Bacteria are prokaryotes: their DNA is not enclosed in a nucleus. They contain cytoplasm, a membrane and a cell wall, and may carry small DNA rings called plasmids. Specialised cells have structures suited to a job: sperm have a tail and many mitochondria; root hair cells have a large surface area for absorption. Not every plant cell has chloroplasts.'],
   ['Microscopes and scale','Magnification = image size ÷ actual size. Convert both measurements to the same unit before dividing: 1 mm = 1,000 micrometres. Resolution is the ability to distinguish two close points. Electron microscopes resolve smaller structures than light microscopes. A clear biological drawing uses single outlines, accurate proportions and labels, rather than shading.'],
   ['Diffusion and osmosis','Diffusion is the net movement of particles from a higher concentration to a lower concentration. It is faster with a steeper concentration gradient, a higher temperature or a larger surface area. Osmosis is the net movement of water through a partially permeable membrane from a more dilute solution to a more concentrated solution. Water entering a plant cell helps make it turgid.'],
   ['Active transport and exchange','Active transport moves substances against their concentration gradient and requires energy transferred by respiration. Root hair cells can absorb mineral ions from dilute soil water this way. Thin exchange surfaces shorten the diffusion distance. Larger organisms have a smaller surface-area-to-volume ratio and need specialised exchange and transport systems.'],
   ['Division and stem cells','Before mitosis, DNA is copied. Chromosomes are separated and the cell divides, producing two genetically identical daughter cells for growth, repair or asexual reproduction. Stem cells can divide and differentiate. Embryonic stem cells can form many cell types; adult stem cells have a more limited range. Consider benefits, rejection or tumour risks, and ethical arguments when evaluating treatment.']
  ], key:['nucleus','ribosome','prokaryote','resolution','osmosis','active transport','mitosis'],
  visual:'Image size ÷ actual size = magnification',
  challenge:'A cell image measures 36 mm and its actual length is 60 micrometres. Calculate its magnification and explain your unit conversion.'
 },
 'Organisation': {
  sections:[
   ['From cells to organ systems','Similar cells work together in tissues. Different tissues form organs; organs cooperate in organ systems. In digestion, large insoluble molecules are broken into smaller soluble molecules that can be absorbed into the blood. The small intestine has villi with a large surface area, a thin surface and a good blood supply.'],
   ['Enzymes and digestion','Enzymes are biological catalysts. A substrate binds to a complementary active site. Carbohydrases break carbohydrates into sugars; proteases break proteins into amino acids; lipases break lipids into fatty acids and glycerol. Temperature increases rate up to an optimum, but excessive heat alters the active site: the enzyme is denatured. Extreme pH can also change its shape.'],
   ['Bile and the digestive system','Bile is made in the liver and stored in the gall bladder. It neutralises stomach acid and emulsifies fats into smaller droplets, increasing the surface area for lipase. Bile is not an enzyme. The pancreas produces digestive enzymes; the large intestine absorbs water from material that has not been digested.'],
   ['The heart and blood','The right side of the heart pumps blood to the lungs; the left pumps it around the body. Valves prevent backflow. Arteries carry blood away from the heart; veins return it. Capillaries have thin walls for exchange. Red blood cells carry oxygen using haemoglobin, white blood cells defend against pathogens, platelets help clotting, and plasma transports dissolved substances.'],
   ['Gas exchange and health','Alveoli offer a large moist surface, short diffusion distance and a good blood supply. Ventilation maintains concentration gradients. Coronary arteries supply heart muscle; narrowing reduces its oxygen supply. Stents and medicines can reduce risks, but each treatment has limits. A correlation between a risk factor and disease does not on its own prove causation.'],
   ['Transport in plants','Xylem carries water and mineral ions from roots upwards. Phloem transports dissolved sugars between sources and places where they are used or stored; this is translocation. Water evaporates from leaves and diffuses out through stomata, creating a transpiration stream. Higher temperature, air movement and light can increase water loss; greater humidity usually reduces it.']
  ],key:['enzyme','active site','villus','haemoglobin','xylem','phloem'],visual:'Body → right heart → lungs → left heart → body',challenge:'Explain why exercise increases the demand for both ventilation and blood flow.'
 },
 'Infection & Response': {
  sections:[
   ['Pathogens and transmission','Pathogens cause infectious disease. Bacteria can reproduce rapidly and release toxins; viruses reproduce inside living cells and can damage them. Fungi and protists can also cause disease. Transmission may involve droplets, contaminated food or water, direct contact or a vector. Match a control measure to the transmission route.'],
   ['Defences and immunity','Skin provides a barrier; blood clots seal breaks. Mucus traps particles and cilia move mucus out of airways. Stomach acid kills many swallowed pathogens. White blood cells can engulf pathogens, make specific antibodies or produce antitoxins. Antibodies bind to matching antigens; they do not work equally against every pathogen.'],
   ['Vaccination and antibiotics','Vaccination introduces antigens without causing the full disease, stimulating immune memory. A later response to that pathogen is faster. Antibiotics act against bacteria, not viruses. Painkillers relieve symptoms without necessarily removing the cause. Resistant bacteria can survive treatment and reproduce, so antibiotic use must be appropriate.'],
   ['Developing medicines','Candidate medicines are investigated for toxicity, effectiveness and suitable dose. Preclinical work uses cells, tissues and sometimes animals. Clinical trials progress to volunteers and patients under controlled conditions. Random allocation and double-blind designs reduce bias. A placebo provides a comparison where it is ethical to use one.'],
   ['Plant disease and defence','Plant disease may cause discolouration, abnormal growth or reduced yield. Physical barriers include cell walls and waxy cuticles; some plants produce antimicrobial chemicals. Mineral deficiency can resemble disease: lack of magnesium can reduce chlorophyll. Use observations and tests before deciding that a pathogen is responsible.'],
   ['Interpreting evidence','When comparing treatments, examine sample size, variation, control groups and possible confounding variables. Calculate a percentage reduction relative to the starting value. A larger inhibition zone in a microbial test may suggest a stronger effect under those conditions, but diffusion rate and concentration also affect the result.']
  ],key:['pathogen','antigen','antibody','vaccine','antibiotic','placebo'],visual:'Antigen → specific immune response → immune memory',challenge:'Explain why an antibiotic does not treat a viral infection, then suggest how symptoms might still be managed.'
 },
 'Bioenergetics': {
  sections:[
   ['Photosynthesis','Photosynthesis transfers light energy into a chemical energy store. Carbon dioxide and water are used to make glucose and oxygen. Chlorophyll absorbs light in chloroplasts. Plants use glucose in respiration, store it as starch, build cellulose and make other biological molecules. Nitrate ions provide nitrogen needed to make amino acids.'],
   ['Limiting factors','Light intensity, carbon dioxide concentration and temperature can limit photosynthesis. Increasing one factor only increases the rate if that factor was limiting. A graph that levels off suggests another limit. In a greenhouse, extra light or heat may increase growth, but growers must balance the benefit against cost.'],
   ['Aerobic respiration','Aerobic respiration uses glucose and oxygen and produces carbon dioxide and water. It transfers energy for processes such as muscle contraction, active transport and maintaining temperature. Respiration occurs in living cells all the time, including in plants; it is not the same process as breathing.'],
   ['Anaerobic respiration','When oxygen supply is insufficient, muscles can respire anaerobically: glucose is broken down to lactic acid, with less energy transferred per molecule of glucose than in aerobic respiration. Yeast can break down glucose into ethanol and carbon dioxide. This fermentation is useful in bread-making and alcoholic drink production.'],
   ['Exercise and metabolism','Exercise raises heart and breathing rates to supply oxygen and glucose and remove carbon dioxide. Metabolism is the sum of the chemical reactions in an organism, including building and breaking down molecules. Protein synthesis, respiration and converting glucose into storage molecules are all metabolic processes.'],
   ['Measuring a biological rate','Rate = quantity of change ÷ time. In a pondweed investigation, oxygen volume per minute is more informative than bubble count if bubble sizes vary. Keep temperature and carbon dioxide supply controlled. Repeat measurements and calculate a mean, investigating unusual readings rather than deleting them automatically.']
  ],key:['chlorophyll','limiting factor','aerobic','anaerobic','metabolism'],visual:'Carbon dioxide + water —light→ glucose + oxygen',challenge:'A plant produces 12 cm³ of oxygen in 4 minutes. Calculate its rate, then suggest why doubling light intensity may not double the rate.'
 },
 'Homeostasis & Response': {
  sections:[
   ['Keeping conditions stable','Homeostasis regulates internal conditions within suitable limits. Control systems use receptors to detect changes, coordination centres to process information and effectors to produce responses. Nervous signals are rapid electrical impulses along neurones; hormones are chemical messengers carried in blood to target organs.'],
   ['Reflexes and the nervous system','In a reflex arc, a receptor detects a stimulus, a sensory neurone carries an impulse to the central nervous system, and a motor neurone carries an impulse to an effector. A relay neurone often links them. Reflexes are rapid and automatic. At a synapse, a chemical messenger crosses the gap between neurones.'],
   ['Blood glucose','Insulin is released by the pancreas when blood glucose rises and helps reduce the concentration. Type 1 diabetes involves insufficient insulin production; Type 2 involves reduced sensitivity to insulin. Treatments differ and are managed individually. Avoid confusing the cause of a disease with a factor that increases its risk.'],
   ['Reproduction and hormones','Puberty involves changes driven by hormones. The menstrual cycle coordinates egg maturation, ovulation and the uterine lining. Oestrogen and progesterone are involved. Contraceptive methods may prevent sperm reaching an egg, prevent ovulation or alter conditions needed for pregnancy. Evaluate effectiveness and limitations, rather than assuming every method works in the same way.'],
   ['Plant responses','Shoots respond to light and gravity; roots also respond to gravity. These responses help plants obtain resources. Growth regulators coordinate changes in growth. When designing a seedling experiment, keep seed type, temperature, water and age consistent and change the light or orientation systematically.'],
   ['Reaction-time investigations','A falling-ruler test estimates reaction time from the distance the ruler falls before it is caught. Keep starting position and instructions consistent. Repeat trials because attention and anticipation cause variation. Practice effects can influence the results, so control the order of testing or include practice trials.']
  ],key:['homeostasis','receptor','effector','synapse','insulin','hormone'],visual:'Change → receptor → coordination centre → effector → response',challenge:'Compare a rapid reflex with a hormonal response, including how each signal travels.'
 },
 'Inheritance': {
  sections:[
   ['DNA, genes and chromosomes','DNA carries genetic information. A gene is a section of DNA associated with a functional product, often a protein. Chromosomes are long DNA molecules associated with proteins. The genome is all an organism’s genetic material. Different versions of a gene are called alleles.'],
   ['Sexual and asexual reproduction','Sexual reproduction involves fusion of gametes and produces genetically varied offspring. Asexual reproduction uses one parent and produces genetically identical offspring, apart from mutations. Meiosis produces gametes with half the usual chromosome number; fertilisation restores the full number. Mitosis maintains chromosome number.'],
   ['Genetic crosses','A dominant allele is expressed when one copy is present; a recessive allele is expressed when there are two copies in a simple single-gene model. Homozygous means two identical alleles and heterozygous means two different alleles. A Punnett square predicts probabilities, not a guaranteed sequence of births.'],
   ['Variation and mutation','Variation may be genetic, environmental or a combination. Mutations change DNA. Most have little or no effect on phenotype, some are harmful and a few can be advantageous in a particular environment. Mutations do not arise because an organism needs a useful characteristic.'],
   ['Selection and evolution','Inherited variation means some individuals are better suited to a particular environment. They may survive and reproduce more successfully, passing on their alleles. Over many generations, the frequency of these alleles can increase. This natural selection can lead to evolution. Extinction occurs when no individuals of a species remain.'],
   ['Selective breeding and genetic engineering','Selective breeding chooses parents with desired features over many generations; it can reduce genetic diversity and increase inherited problems. Genetic engineering changes an organism’s DNA more directly. Evaluate possible benefits, environmental consequences and ethical questions using evidence, rather than assuming a technique is always beneficial or always harmful.'],
   ['Evidence and classification','Fossils provide evidence of past organisms, although the record is incomplete. DNA comparisons help infer evolutionary relationships. Classification groups organisms according to shared features and relationships; new evidence can change a classification. Binomial names use a genus and a species name.']
  ],key:['allele','genotype','phenotype','meiosis','mutation','natural selection'],visual:'Aa × Aa → AA, Aa, Aa, aa',challenge:'Two heterozygous parents carry a recessive allele. Explain why the probability of a recessive phenotype is one in four for each offspring.'
 },
 'Ecology': {
  sections:[
   ['Communities and ecosystems','A population is all organisms of one species in an area. A community contains populations of different species. An ecosystem includes the community and its physical environment. Organisms depend on one another for resources, pollination, shelter or food; a change to one population may affect several others.'],
   ['Competition and adaptation','Animals may compete for food, mates and territory; plants compete for light, water, mineral ions and space. Abiotic factors include temperature, moisture and light. Biotic factors include predators, disease and competitors. Structural, behavioural and functional adaptations can improve survival in a particular environment.'],
   ['Food chains and biomass','Producers form the first trophic level of a food chain. Arrows show the direction in which biomass is transferred when organisms are eaten. Not all biomass becomes biomass in the next level: some is uneaten, some is lost in waste, and some is used in respiration. Energy is transferred to the surroundings; matter can be recycled.'],
   ['Carbon, water and decay','Photosynthesis removes carbon dioxide from the atmosphere. Feeding transfers carbon between organisms; respiration and combustion return carbon dioxide. Decomposers break down dead material and waste. Decay is affected by temperature, moisture and oxygen availability. Water cycles through evaporation, condensation, precipitation and movement through living organisms.'],
   ['Sampling and fieldwork','Use randomly placed quadrats to estimate abundance without choosing only interesting patches. A transect samples changes along an environmental gradient. Estimate population size as mean number per quadrat × total area ÷ quadrat area, using compatible units. Larger representative samples usually give a more reliable estimate.'],
   ['Biodiversity and food security','Biodiversity is the variety of living organisms. Habitat loss, pollution and climate change can reduce it. Conservation can protect habitats and breeding populations, but involves social and economic decisions. Food security depends on sufficient, safe food and can be affected by population growth, pests, conflict, climate and farming practices.'],
   ['Evaluating interventions','Compare the benefits and costs of an intervention, using evidence. Restoring a habitat may support biodiversity and reduce flood risk, but need land and funding. Sustainable approaches aim to meet current needs while maintaining resources and ecosystem functions for the future.']
  ],key:['population','community','abiotic','quadrat','trophic level','biodiversity'],visual:'Producer → primary consumer → secondary consumer',challenge:'A 0.25 m² quadrat contains a mean of 6 plants. Estimate the population in 50 m² and identify one assumption.'
 }
};
BIOLOGY_UNITS['Cells and Control']={...BIOLOGY_UNITS['Homeostasis & Response'],sections:[BIOLOGY_UNITS['Cell Biology'].sections[5],BIOLOGY_UNITS['Homeostasis & Response'].sections[1],['Growth and differentiation','Growth may involve cell division, cell enlargement and differentiation. Stem cells produce specialised cells; in plants, meristems remain capable of division. A growth curve shows how a measurement changes with age, but comparing individuals also requires attention to variation.'],['The brain and the eye','The brain coordinates complex activities. Different regions have different roles. In the eye, the retina detects light; the optic nerve carries impulses to the brain. The iris changes pupil size to control light entry. The lens focuses light on the retina. Nervous tissue can be difficult to repair, so damage may have lasting effects.']],key:['mitosis','differentiation','neurone','synapse','retina'],visual:'Receptor → sensory neurone → CNS → motor neurone → effector',challenge:'Explain how mitosis and differentiation contribute differently to growth.'};
BIOLOGY_UNITS['Natural Selection']={...BIOLOGY_UNITS.Inheritance,sections:BIOLOGY_UNITS.Inheritance.sections.slice(3),challenge:'Explain how antibiotic resistance can become more common without bacteria choosing to become resistant.'};

// Questions are shared only through explicit board-topic routes below.
const BIOLOGY_PRACTICE=[];
function bioQ(topic,id,q,answer,explain,extra={}){BIOLOGY_PRACTICE.push({id:'bio2-'+id,subject:'Biology',topic,q,answer,explain,type:'writing',marks:2,level:2,tier:'both',style:'Explain and apply',...extra});}
const bioPrompts={
 'Cell Biology':[
 ['ribosome','Which cell structure makes proteins?','Ribosomes','Ribosomes assemble amino acids into proteins.',{type:'mcq',level:1,marks:1,options:['Mitochondria','Ribosomes','Vacuoles','Cell walls']}],
 ['bacteria','Give two differences between a bacterial cell and a typical animal cell.','Bacterial DNA is not enclosed in a nucleus. Bacteria have a cell wall; animal cells do not.','Award one point for each correct comparison. Bacteria can also have plasmids.'],
 ['osmosis','A potato cylinder gains mass in distilled water. Explain why.','Water moves into its cells by osmosis through partially permeable membranes, from the more dilute external solution.','Link the direction of net water movement to the concentration difference.'],
 ['active','Root cells absorb ions from very dilute soil water. Explain why energy may be needed.','Ions may move against their concentration gradient by active transport, which requires energy from respiration.','The concentration gradient, rather than simply the size of an ion, explains the energy requirement.'],
 ['micro','A cell image is 15 mm long. The real cell is 0.03 mm long. Calculate magnification.','500','15 ÷ 0.03 = 500; magnification has no unit.',{type:'short',accepted:['500','500x','x500','500×','×500'],style:'Calculation'}],
 ['surface','Explain two ways a thin, folded exchange surface improves diffusion.','Folding increases surface area; a thin surface reduces diffusion distance.','Award one point for each structure linked to its effect.'],
 ['mitosis','How do the chromosome numbers and genetic information of daughter cells produced by mitosis compare?','They normally have the same chromosome number and identical genetic information.','DNA is copied and the copies are separated before the cell divides.'],
 ['stem','Give one potential benefit and one possible risk of using stem cells to replace damaged tissue.','They could replace lost specialised cells; uncontrolled division could form a tumour, or the tissue could be rejected.','A balanced answer links an application to a biological risk.']
 ],
 'Organisation':[
 ['lipase','Which enzyme breaks down lipids?','Lipase','Lipase produces fatty acids and glycerol.',{type:'mcq',level:1,marks:1,options:['Amylase','Lipase','Protease','Bile']}],
 ['denature','Explain why very high temperature reduces enzyme activity.','The active site changes shape, so the substrate no longer fits effectively.','Use denatured, not killed: enzymes are not living organisms.'],
 ['bile','Explain how bile helps digestion without being an enzyme.','It neutralises acid and emulsifies fat, increasing surface area for lipase.','Neutralising acid helps establish suitable conditions in the small intestine.'],
 ['villi','Explain two adaptations of villi for absorption.','A large surface area increases absorption; a thin surface shortens diffusion distance. A blood supply maintains gradients.','Award credit for two adaptations linked to their effects.'],
 ['valve','What is the function of heart valves?','Prevent backflow of blood','Valves keep blood moving in the required direction.',{type:'mcq',level:1,marks:1,options:['Make oxygen','Prevent backflow of blood','Produce red blood cells','Digest fats']}],
 ['plant-transport','Compare the substances transported in xylem and phloem.','Xylem transports water and mineral ions. Phloem transports dissolved sugars.','Do not describe both as carrying only water.'],
 ['transpiration','Why does increased air movement often increase transpiration?','Moving air removes humid air near the leaf, maintaining a steeper water-vapour concentration gradient.','Link the environmental change to diffusion from the leaf.'],
 ['heart-risk','A study links smoking with heart disease. Why is correlation alone not enough to prove causation?','Other variables may differ between the groups and affect disease risk. Further controlled evidence and a plausible mechanism are needed.','Identify the possibility of confounding factors rather than dismissing all observational evidence.']
 ],
 'Infection & Response':[
 ['virus','Why are antibiotics unsuitable for treating a viral infection?','They act on bacterial structures or processes that viruses do not have.','Viruses reproduce inside host cells; painkillers may relieve symptoms but are not antibiotics.'],
 ['vaccine','Explain why a vaccinated person may respond faster to later infection by the same pathogen.','Vaccination stimulates an immune response and memory cells; later exposure produces a faster specific antibody response.','Link immune memory to the same pathogen or antigen.'],
 ['placebo','What is the purpose of a placebo in a suitable clinical trial?','Provide a comparison for effects unrelated to the active medicine','It helps distinguish the medicine’s effect from expectations and other influences.',{type:'mcq',level:1,marks:1,options:['Guarantee a cure','Provide a comparison for effects unrelated to the active medicine','Replace random allocation','Increase the dose']}],
 ['double-blind','Explain how a double-blind trial reduces bias.','Neither participants nor the people assessing them know which treatment each person receives, reducing expectation and assessment bias.','Both groups being unaware is the key feature.'],
 ['resistance','Explain how antibiotic treatment can increase the proportion of resistant bacteria.','Susceptible bacteria are killed; resistant bacteria survive, reproduce and pass on resistance.','The antibiotic selects among variation; it does not cause a useful mutation because the bacteria need it.'],
 ['transmission','Suggest a way to reduce disease spread by contaminated drinking water and explain it.','Treating drinking water can remove or kill pathogens before they are swallowed.','Match the control to the route of transmission.'],
 ['trial-percent','A treatment reduces cases from 80 to 20. Calculate the percentage reduction.','75','Reduction = 60; 60 ÷ 80 × 100 = 75%.',{type:'short',accepted:['75','75%'],style:'Calculation'}],
 ['zone','Why must antibiotic discs have comparable concentrations when comparing inhibition zones?','Concentration affects the response, so it must be controlled for a fair comparison of the treatments.','A zone size may also depend on diffusion, so avoid assuming size measures effectiveness in every setting.']
 ],
 'Bioenergetics':[
 ['photo-gas','Which gas is a reactant in photosynthesis?','Carbon dioxide','Plants use carbon dioxide and water to produce glucose and oxygen.',{type:'mcq',level:1,marks:1,options:['Oxygen','Nitrogen','Carbon dioxide','Hydrogen']}],
 ['night','Do plants respire at night? Explain your answer.','Yes. Living plant cells need energy and carry out respiration during day and night.','Photosynthesis requires light; respiration does not require light.'],
 ['limit','A photosynthesis graph levels off as light intensity rises. Suggest why.','Another factor, such as carbon dioxide concentration or temperature, now limits the rate.','More light cannot remove a different limiting factor.'],
 ['rate','Pondweed produces 18 cm³ of oxygen in 6 minutes. Calculate the mean rate in cm³ per minute.','3','18 ÷ 6 = 3 cm³ per minute.',{type:'short',accepted:['3','3cm3/min','3cm³/min'],style:'Calculation'}],
 ['anaerobic','Compare aerobic and anaerobic respiration in human muscles.','Aerobic respiration uses oxygen and produces carbon dioxide and water. Anaerobic respiration produces lactic acid and transfers less energy per glucose molecule.','State a contrast in oxygen use and a contrast in products or energy transfer.',{marks:3}],
 ['ferment','Name the two products of anaerobic respiration in yeast.','Ethanol and carbon dioxide','This process is fermentation. Lactic acid is associated with anaerobic respiration in human muscles.'],
 ['glucose-use','Give two uses of glucose in a plant other than respiration.','It can be stored as starch and used to make cellulose. It can also be used to make lipids or, with nitrate-derived nitrogen, amino acids.','Choose two distinct uses.'],
 ['bubbles','Why can oxygen volume be a better measure than bubble count?','Bubbles can have different sizes; volume measures the quantity of gas more directly.','Still control temperature and the measurement period.']
 ],
 'Homeostasis & Response':[
 ['effector','Which structure can act as an effector?','A muscle','Muscles contract and glands secrete in response to signals.',{type:'mcq',level:1,marks:1,options:['A light ray','A muscle','A stimulus','An impulse']}],
 ['reflex','Explain why withdrawing a hand from a hot surface can happen quickly without a conscious decision.','A reflex arc coordinates a rapid automatic response through the nervous system without waiting for conscious processing.','The receptor, neurones and effector form a response pathway.'],
 ['synapse','How does a signal cross a synapse?','A chemical messenger is released, diffuses across the gap and triggers a response in the next neurone.','Electrical impulses travel along neurones; chemical transmission crosses the gap.'],
 ['insulin','Which organ releases insulin?','Pancreas','The pancreas responds to changes in blood glucose.',{type:'mcq',level:1,marks:1,options:['Liver','Kidney','Pancreas','Lung']}],
 ['diabetes','Compare the underlying problems in Type 1 and Type 2 diabetes.','Type 1 involves insufficient insulin production; Type 2 involves reduced responsiveness to insulin.','These are different problems even though both can result in raised blood glucose.'],
 ['signals','Give two differences between nervous and hormonal communication.','Nervous signals travel as impulses along neurones and are usually rapid. Hormones travel in blood and their effects may be slower and longer-lasting.','Compare the route and typical time course.'],
 ['reaction','Why should a student repeat a ruler-drop reaction-time test?','Reaction time varies between trials; repeats allow a mean and help identify variation or unusual results.','Repeats alone do not remove a systematic error.'],
 ['plant-light','Why does a shoot growing towards light benefit a plant?','Its leaves may receive more light, increasing photosynthesis when light is limiting.','Connect the growth response to obtaining a resource.']
 ],
 'Inheritance':[
 ['allele','What is an allele?','A version of a gene','Different alleles can contribute to differences in phenotype.',{type:'mcq',level:1,marks:1,options:['A whole organism','A version of a gene','A type of organ','A cell membrane']}],
 ['cross','In a simple dominant/recessive model, two Aa parents have an offspring. What is the probability of aa?','1/4','The possible combinations are AA, Aa, Aa and aa.',{type:'short',accepted:['1/4','0.25','25%'],style:'Genetic calculation'}],
 ['meiosis','Explain why gametes need half the usual chromosome number.','At fertilisation two gametes fuse, restoring the full chromosome number rather than doubling it each generation.','Meiosis reduces chromosome number.'],
 ['twins','Identical twins can have different body masses. Suggest why.','Environmental factors, such as diet and activity, can affect phenotype even when genetic information is very similar.','Variation is not always caused by different alleles.'],
 ['selection','Explain how a helpful inherited feature can become more common over many generations.','Individuals with it may survive and reproduce more successfully, passing on the relevant alleles to more offspring.','Name inherited variation, differential reproductive success and inheritance.',{marks:3}],
 ['breeding','Give one risk of repeatedly breeding closely related individuals for a desired feature.','Genetic diversity can fall and harmful recessive alleles may be more likely to be inherited in pairs.','The desired characteristic is not the only genetic information being inherited.'],
 ['fossils','Why is the fossil record incomplete?','Many organisms never fossilised, and some fossils have been destroyed or have not been discovered.','Soft-bodied organisms and unsuitable preservation conditions contribute to gaps.'],
 ['probability','A couple already has a child with a recessive condition. Does this change the one-in-four probability for their next child in the same simple cross? Explain.','No. Each fertilisation is a separate event; the previous birth does not change the parental alleles or the probability.','A probability does not mean exactly one affected child in every four births.']
 ],
 'Ecology':[
 ['abiotic','Which is an abiotic factor?','Temperature','Abiotic factors are non-living environmental conditions.',{type:'mcq',level:1,marks:1,options:['Predators','Competition','Temperature','Disease organisms']}],
 ['quadrat','Why should quadrats be placed randomly when estimating abundance across a field?','Random placement reduces selection bias and helps sample the area representatively.','Choosing only patches containing many organisms inflates the estimate.'],
 ['population','A 0.5 m² quadrat contains a mean of 4 plants. Estimate the number in 100 m².','800','4 × 100 ÷ 0.5 = 800 plants.',{type:'short',accepted:['800','800plants'],style:'Sampling calculation'}],
 ['transect','When is a transect more useful than unrelated random quadrats?','When investigating how abundance changes along an environmental gradient, such as distance from a path.','Sampling at known positions links organisms to the gradient.'],
 ['carbon','Explain how carbon moves from the atmosphere into an animal and back to the atmosphere.','Plants take in carbon dioxide in photosynthesis. Feeding transfers carbon to animals; respiration returns carbon dioxide.','Include the processes and their directions.',{marks:3}],
 ['decay','Why does low temperature usually slow decay?','Decomposer enzyme activity and growth are slower, so dead material is broken down more slowly.','Very cold conditions do not necessarily kill every decomposer.'],
 ['biomass','Explain why only some biomass is transferred to the next trophic level.','Some material is not eaten or digested; some is lost in waste, and some is used in respiration.','Do not say energy is destroyed.'],
 ['biodiversity','Give one benefit and one possible cost of restoring a wetland.','It may provide habitat and improve biodiversity; it may require land, money or changes to existing land use.','A justified evaluation considers ecological and human consequences.']
 ]
};
for(const [topic,items] of Object.entries(bioPrompts))for(const [id,q,a,e,extra] of items)bioQ(topic,id,q,a,e,extra||{});
const BIO_PRACTICALS = {
 microscopy:{title:'Microscopy',topic:'Cell Biology',aim:'Observe cells and calculate magnification.',method:'Begin with low power, focus carefully and then increase magnification. Make a clear labelled drawing of visible structures. Measure the image and convert image and actual size to the same unit.',controls:'Compare images at a known magnification. Distinguish increased image size from improved resolution.',example:'A 30 mm image of a 0.05 mm cell has magnification 30 ÷ 0.05 = 600.',pitfall:'Magnification is a ratio, not a length.',refs:{aqa:'Required practical 1',edexcel:'Core practical 1.6',ocr:'Microscopy skills'}},
 osmosis:{title:'Osmosis in plant tissue',topic:'Cell Biology',aim:'Investigate how solution concentration affects water movement.',method:'Compare equal-sized plant-tissue pieces in a range of solution concentrations. Record initial and final mass after the same time, blotting consistently before weighing. Repeat each concentration.',controls:'Keep tissue source, dimensions, temperature, time and solution volume consistent.',example:'A piece changes from 2.0 g to 2.3 g: percentage change = (0.3 ÷ 2.0) × 100 = +15%.',pitfall:'Use initial mass as the denominator. At zero percentage mass change there is no net water movement.',refs:{aqa:'Required practical 3',edexcel:'Core practical 1.16',ocr:'Transport and measurement skills'}},
 food:{title:'Food tests',topic:'Organisation',aim:'Identify major groups of biological molecules.',method:'Iodine changes from orange-brown to blue-black with starch. Benedict’s reagent, heated in a water bath, changes from blue towards a coloured precipitate with reducing sugars. The Biuret test gives a lilac/purple result with protein. A lipid emulsion test gives a cloudy white emulsion; Sudan III forms a red-stained oil layer when lipids are present. Follow the method specified by your course.',controls:'Use separate samples, clean apparatus and known positive/negative controls.',example:'A blue-black iodine result supports the presence of starch; it does not identify every carbohydrate.',pitfall:'A negative starch test does not show that a food contains no sugar.',refs:{aqa:'Required practical 4',edexcel:'Core practical 1.13B · lipid emulsion test',ocr:'Biological molecule testing skills'}},
 enzymes:{title:'Enzymes and pH',topic:'Organisation',aim:'Investigate how pH affects amylase activity.',method:'Compare starch breakdown at different pH values, using regular samples tested with iodine. Record the time until starch is no longer detected. Repeat each pH and compare rates using 1 ÷ time.',controls:'Keep temperature, enzyme concentration, starch concentration, volumes and sampling intervals consistent.',example:'An endpoint at 40 s gives an estimated relative rate of 1/40 = 0.025 s⁻¹.',pitfall:'Shorter reaction time means a faster rate, not a slower one.',refs:{aqa:'Required practical 5',edexcel:'Core practical 1.10',ocr:'Enzyme investigation skills'}},
 microbes:{title:'Antimicrobial investigations',topic:'Infection & Response',aim:'Interpret the effect of different treatments on microbial growth.',method:'In a supervised school investigation, compare zones without visible growth around treatment discs on a culture. Use your teacher’s approved culture, aseptic technique, incubation and disposal procedure. Do not culture unknown organisms at home.',controls:'Use a control disc and comparable disc size, treatment concentration and measurement method.',example:'A circular zone with radius 5 mm has area π × 5² ≈ 78.5 mm².',pitfall:'Diameter is twice the radius. Zone size is also affected by diffusion.',refs:{aqa:'Required practical 2',edexcel:'Core practical 5.18B',ocr:'Microbial investigation skills'}},
 photosynthesis:{title:'Photosynthesis and light',topic:'Bioenergetics',aim:'Investigate how light affects photosynthetic rate.',method:'Measure oxygen produced by an aquatic plant over a fixed time at different light intensities. Allow time to adjust at each setting. Repeat measurements; a measured gas volume avoids assuming all bubbles have equal size.',controls:'Keep plant material, temperature, measurement time and carbon dioxide supply consistent.',example:'15 cm³ in 5 minutes is 3 cm³ per minute.',pitfall:'Moving a lamp can change temperature as well as light intensity.',refs:{aqa:'Required practical 6',edexcel:'Core practical 6.5',ocr:'Photosynthesis investigation skills'}},
 reaction:{title:'Reaction time',topic:'Homeostasis & Response',aim:'Investigate a factor that may affect human reaction time.',method:'Use a consistent ruler-drop arrangement and record catching distance. Include repeated trials and compare means. Use appropriate conversion information if reporting time rather than distance.',controls:'Keep hand position, ruler start point and instructions the same. Consider anticipation and practice effects.',example:'An unusually short distance may reflect anticipation rather than a true improvement.',pitfall:'Use safe, voluntary testing. Do not use medicines or stimulants as experimental treatments.',refs:{aqa:'Required practical 7',ocr:'Human-response investigation skills'}},
 seedlings:{title:'Seedling responses',topic:'Homeostasis & Response',aim:'Compare growth responses to light or gravity.',method:'Compare seedlings with one changed condition, such as light direction. Record growth or direction at consistent intervals. Use enough seedlings to show variation.',controls:'Keep species, age, water, temperature and the observation period consistent.',example:'Growth towards a side light can be compared with growth under even lighting.',pitfall:'An observed response must be distinguished from pre-existing differences between seedlings.',refs:{aqa:'Required practical 8',ocr:'Plant-response investigation skills'}},
 fieldwork:{title:'Quadrats and transects',topic:'Ecology',aim:'Estimate abundance or examine a change along a gradient.',method:'Use random coordinates for an area estimate. Use a belt transect to examine a gradient, recording organisms at known distances. Record quadrat area and repeat sufficiently to represent variation.',controls:'Use the same counting rule and quadrat size; record relevant environmental conditions.',example:'Mean 5 plants in 0.25 m² over 20 m² gives 5 × 20 ÷ 0.25 = 400 plants.',pitfall:'An estimate assumes the sampled area represents the whole area.',refs:{aqa:'Required practical 9',edexcel:'Core practical 9.5',ocr:'Ecological sampling skills'}},
 decay:{title:'Decay and temperature',topic:'Ecology',aim:'Investigate a factor affecting decomposition.',method:'In a supervised model investigation, compare the time taken for a defined indicator change under different temperatures. Repeat readings and relate 1 ÷ time to a relative rate.',controls:'Keep the starting mixtures, volumes, endpoint and timing method consistent.',example:'An endpoint at 50 s gives 0.020 s⁻¹; at 100 s it gives 0.010 s⁻¹.',pitfall:'A model indicator change is evidence of a process, not a direct count of every decomposer.',refs:{aqa:'Required practical 10',ocr:'Decomposition investigation skills'}},
 respiration:{title:'Respiration in living organisms',topic:'Organisation',aim:'Investigate a factor affecting respiration rate.',method:'Use an approved school respirometer arrangement to track gas-volume change over time. Compare appropriate living material and a control. Interpret the measured change using the way the apparatus is set up.',controls:'Keep temperature stable, use equal quantities of material and check for leaks.',example:'A volume change of 0.6 cm³ in 3 minutes represents 0.2 cm³ per minute under the measurement conditions.',pitfall:'Temperature or pressure changes can move a fluid marker without a biological change.',refs:{edexcel:'Core practical 8.11',ocr:'Respiration investigation skills'}}
};
const BIO_HIGHER={
 'Cell Biology':['Surface-area-to-volume reasoning','A cube with side 1 has surface area 6 and volume 1: its ratio is 6:1. Doubling the side gives area 24 and volume 8, a ratio of 3:1. The decreasing ratio helps explain why diffusion alone becomes insufficient as organisms get larger.'],
 'Organisation':['Using exchange gradients','Rapid blood flow can maintain a concentration difference at an exchange surface. When analysing a system, distinguish the mechanism that moves blood from the diffusion of molecules between blood and tissues. A large surface is only helpful if other conditions allow exchange.'],
 'Infection & Response':['Monoclonal antibodies','Monoclonal antibodies bind to a specific antigen and can be used in diagnosis or to target substances in treatment. Their specificity is useful, but treatment can still cause side effects. A test result also needs interpretation in the context of its sensitivity and possible false results.'],
 'Bioenergetics':['Interacting limiting factors','Light intensity from a point source can be modelled as proportional to 1 ÷ distance². Doubling distance gives one-quarter of the intensity in that model. Photosynthetic rate need not fall to one-quarter because another factor may limit it and real lamps do not perfectly match the model.'],
 'Homeostasis & Response':['Hormonal feedback','When blood glucose is too low, glucagon promotes conversion of stored glycogen to glucose in the liver. Insulin promotes removal of glucose from blood when it is too high. Opposing responses help restore a suitable range. Negative feedback reduces the original change; it does not mean that a process is harmful.'],
 'Inheritance':['DNA and protein structure','The sequence of DNA bases influences the order of amino acids in a protein. A mutation may alter the sequence and change protein shape, potentially affecting an enzyme’s active site. Some changes do not affect the amino-acid sequence or occur in regions with no immediate observable effect.'],
 'Ecology':['Transfer efficiency','Biomass transfer efficiency = biomass transferred to the next level ÷ biomass at the previous level × 100. If 40 kg becomes 6 kg in the next level, efficiency is 15%. Do not add biomass from different levels as if it represents an extra supply of food.']
};
const BIO_BOARD_EXTRA={
 aqa:{
 'Infection & Response':[['Disease examples','Measles is a viral disease spread through droplets; vaccination helps prevention. HIV attacks the immune system. Salmonella is a bacterial cause of food poisoning; gonorrhoea is sexually transmitted and bacterial. Malaria is caused by a protist transmitted by mosquitoes. Tobacco mosaic virus affects plants; rose black spot is a fungal disease. Match each pathogen to its transmission and control.']],
 'Homeostasis & Response':[['Temperature and water balance','Sweating and increased blood flow near the skin help transfer heat to the surroundings. Shivering increases heat production. The kidneys remove urea and regulate water and ion balance. Dialysis and transplantation can treat kidney failure but have different practical demands and risks.'],['The eye','The retina contains light-sensitive cells. The iris controls pupil size, and the lens focuses light on the retina. Changes in lens shape help focus at different distances. Corrective lenses can help when an image is focused in front of or behind the retina.']],
 'Inheritance':[['Evolution and its evidence','Natural selection was developed through the work of scientists including Darwin and Wallace. Fossils, resistant bacteria and genetic evidence support evolution. Separation of populations can allow differences to accumulate and may eventually contribute to speciation. Scientific explanations are tested against evidence.']]
 },
 edexcel:{
 'Cell Biology':[['Food energy','Food calorimetry uses energy transferred from burning a food sample to heat water. Energy transfer can be estimated from water mass, temperature rise and specific heat capacity. Heat lost to the surroundings means a simple school result usually underestimates the food’s energy content.']],
 'Natural Selection':[['Evidence for human evolution','Fossils and stone tools provide evidence about past humans and their relatives. Anatomical features can suggest movement or diet, but incomplete remains create uncertainty. More recent evidence may refine the dates and relationships inferred from older discoveries.'],['Biotechnology','Useful biological products may be made using microorganisms in controlled conditions. Temperature, nutrient supply and contamination need control. Selective breeding and genetic engineering are different ways of changing inherited characteristics; weigh evidence about benefits and possible consequences.']],
 'Homeostasis & Response':[['Water balance and the kidneys','The kidneys filter blood, remove urea and regulate water balance. Useful substances are reabsorbed. If kidneys fail, dialysis removes some waste and restores aspects of chemical balance; a transplant can provide ongoing kidney function but involves surgery and immune-system issues.']]
 },
 ocr:{
 'Infection & Response':[['Global challenges','Protecting health links the spread of pathogens, immune responses and the evidence for treatment. Population growth also creates food-production challenges. Evaluate biological solutions using benefits, uncertainties and consequences rather than a single headline claim.']],
 'Ecology':[['Monitoring environmental change','Use comparable sampling methods over time to distinguish real ecological change from differences in measurement. Consider abiotic conditions and human activity together. Conservation decisions may combine evidence from species abundance, habitat quality and long-term trends.']],
 'Inheritance':[['Genes and selection','Relate DNA, proteins and phenotype to inherited variation. Evolutionary relationships can be represented as branching diagrams. The branches represent inferred relationships, not a ladder of organisms becoming more advanced.']]
 }
};
// Route shared sections and practice to the correct Edexcel umbrella topics.
function bioRoute(topic,id,board){
 if(board==='ocr'){
  if(topic==='Organisation'&&['lipase','denature'].includes(id))return 'Cell Biology';
  if(topic==='Cell Biology'&&['osmosis','active','surface','mitosis','stem'].includes(id))return 'Organisation';
  return topic;
 }
 if(board!=='edexcel')return topic;
 if(topic==='Organisation'&&['lipase','denature','bile','villi'].includes(id))return 'Cell Biology';
 if(topic==='Cell Biology'&&['mitosis','stem'].includes(id))return 'Cells and Control';
 if(topic==='Homeostasis & Response'&&['reflex','synapse','reaction'].includes(id))return 'Cells and Control';
 if(topic==='Inheritance'&&['selection','breeding','fossils'].includes(id))return 'Natural Selection';
 if(topic==='Bioenergetics'&&['night','anaerobic','ferment'].includes(id))return 'Organisation';
 return topic;
}
for(const board of ['common','aqa','edexcel','ocr']){
 const pack=PACKS.Biology[board];
 for(const t of pack.topics){
  const base=BIOLOGY_UNITS[t.id];if(!base)continue;
  let sections=base.sections.map(([title,body])=>({title,body,tier:'both'}));
  if(board==='edexcel'){
   if(t.id==='Cell Biology')sections=[...sections.slice(0,5),...BIOLOGY_UNITS.Organisation.sections.slice(0,3).map(([title,body])=>({title,body,tier:'both'}))];
   if(t.id==='Organisation')sections=[...BIOLOGY_UNITS.Organisation.sections.slice(3,5),...BIOLOGY_UNITS.Bioenergetics.sections.slice(2,5)].map(([title,body])=>({title,body,tier:'both'}));
   if(t.id==='Bioenergetics')sections=[...BIOLOGY_UNITS.Bioenergetics.sections.slice(0,2),BIOLOGY_UNITS.Organisation.sections[5],BIOLOGY_UNITS.Bioenergetics.sections[5]].map(([title,body])=>({title,body,tier:'both'}));
   if(t.id==='Inheritance')sections=sections.slice(0,4);
   if(t.id==='Homeostasis & Response')sections=sections.filter(x=>!['Reflexes and the nervous system','Reaction-time investigations'].includes(x.title));
  }
  if(board==='ocr'){
   if(t.id==='Cell Biology')sections=[...BIOLOGY_UNITS['Cell Biology'].sections.slice(0,3),BIOLOGY_UNITS.Organisation.sections[1]].map(([title,body])=>({title,body,tier:'both'}));
   if(t.id==='Organisation')sections=[...BIOLOGY_UNITS['Cell Biology'].sections.slice(3),...BIOLOGY_UNITS.Organisation.sections.filter((section,i)=>i!==1)].map(([title,body])=>({title,body,tier:'both'}));
  }
  const previous=pack.overrides[t.id];
  if(t.id==='Cell Biology'&&previous?.ref)sections.push({title:'Your board · microscopy',body:microscopy[board][1],tier:'both'});
  for(const [title,body] of BIO_BOARD_EXTRA[board]?.[t.id]||[])sections.push({title,body,tier:'both'});
  // Higher extensions are additional practice, not a claim of identical tier boundaries across boards.
  if(BIO_HIGHER[t.id])sections.push({title:BIO_HIGHER[t.id][0],body:BIO_HIGHER[t.id][1],tier:'higher'});
  const practicals=Object.entries(BIO_PRACTICALS).filter(([id,p])=>{
   let target=p.topic;
   if(board==='edexcel'&&['food','enzymes'].includes(id))target='Cell Biology';
   if(board==='ocr'){
    if(['food','enzymes'].includes(id))target='Cell Biology';
    if(id==='osmosis')target='Organisation';
    if(id==='respiration')target='Bioenergetics';
   }
   return target===t.id&&(board==='common'||p.refs[board]);
  }).map(([id,p])=>({id,...p,ref:board==='common'?'Shared practical preparation':p.refs[board]}));
  pack.overrides[t.id]={...base,learn:sections.filter(s=>s.tier==='both').map(s=>s.body).join('\n\n'),sections,practicals,ref:t.unit,minutes:Math.max(8,sections.length*2),objectives:sections.filter(s=>s.tier==='both').map(s=>s.title),source:pack.source||SOURCES.Biology.aqa};
 }
 for(const q of BIOLOGY_PRACTICE){const shortId=q.id.replace('bio2-','');pack.questions.push({...q,topic:bioRoute(q.topic,shortId,board)});}
 pack.note=board==='common'?'Shared Biology revision: lessons, mixed practice and practical preparation. Confirm your board for its course organisation.':'Separate Biology revision with lessons, mixed practice and board-linked practical preparation. Check your official specification for the full examination requirements.';
}
for(const b of ['common','aqa','edexcel','ocr']){
 addQ('Biology',b,'Bioenergetics','bio2-inverse-square','In the inverse-square model, a lamp is moved from 10 cm to 20 cm away. What fraction of the initial light intensity remains?','1/4','Intensity is proportional to 1/distance², so doubling distance gives one-quarter.',{type:'short',accepted:['1/4','0.25','25%'],tier:'higher',level:3,marks:2,style:'Higher extension · modelling'});
 addQ('Biology',b,'Ecology','bio2-efficiency','A trophic level has 80 kg of biomass. The next level gains 12 kg. Calculate transfer efficiency as a percentage.','15','12 ÷ 80 × 100 = 15%.',{type:'short',accepted:['15','15%'],tier:'higher',level:3,marks:2,style:'Higher extension · calculation'});
 addQ('Biology',b,'Homeostasis & Response','bio2-feedback','Explain how glucagon helps restore blood glucose when it is too low.','Glucagon promotes conversion of liver glycogen to glucose, which enters the blood and raises its glucose concentration.','Link the hormone to the store, the conversion and the return towards a suitable concentration.',{type:'writing',tier:'higher',level:3,marks:3,style:'Higher extension · feedback'});
}
// Additional application and endocrine revision, with explicit extension labels.
for(const b of ['common','aqa','edexcel','ocr']){
 const h=PACKS.Biology[b].overrides['Homeostasis & Response'];
 h.sections.push({title:'Reproductive hormones',tier:'both',body:'FSH stimulates maturation of an egg in an ovarian follicle. LH triggers ovulation. Oestrogen and progesterone help coordinate changes in the uterine lining. Distinguish the source of a hormone, the organ it acts on and the effect it produces.'});
 h.sections.push({title:'Hormones, feedback and fertility',tier:'higher',body:'Oestrogen inhibits FSH and can stimulate an LH surge; progesterone helps maintain the uterine lining and inhibits FSH and LH. Falling progesterone allows the lining to break down. Fertility treatment may use hormones to stimulate egg maturation. In IVF, eggs are fertilised outside the body and an embryo is transferred to the uterus. Success is not guaranteed and treatment has physical and emotional demands.'});
 h.sections.push({title:'Regulating water balance',tier:'higher',body:'ADH helps regulate how much water is reabsorbed by the kidneys. When the blood has too little water, more ADH causes more water reabsorption, producing a smaller volume of more concentrated urine. A control response that counters the original change is negative feedback.'});
 h.sections.push({title:'Plant growth regulators',tier:'higher',body:'Unequal distribution of auxin can cause unequal growth on opposite sides of a shoot, so it bends towards light. Roots and shoots respond differently to auxin. Plant growth regulators are used in applications such as rooting powders and selective weed control; connect an application to the growth response it changes.'});
 for(const [topic,id,prompt,answer,explanation,extra] of [
 ['Homeostasis & Response','ovulation','Which hormone triggers ovulation?','LH','LH triggers egg release; FSH promotes maturation.',{type:'mcq',level:1,marks:1,options:['Insulin','LH','ADH','Glucagon']}],
 ['Homeostasis & Response','adh','A person has lost water through sweating. Explain how ADH can reduce further water loss.','More ADH increases water reabsorption in the kidneys, so a smaller volume of more concentrated urine is produced.','Link the hormone to water reabsorption and the resulting change in urine.',{type:'writing',tier:'higher',level:3,marks:3}],
 ['Cell Biology','osmosis-percent','A plant-tissue sample changes from 2.5 g to 2.0 g. Calculate the percentage change in mass.','-20','(2.0 − 2.5) ÷ 2.5 × 100 = −20%.',{type:'short',accepted:['-20','-20%','20%loss'],marks:2}],
 ['Infection & Response','zone-area','An inhibition zone has radius 4 mm. Calculate its area in mm² to one decimal place.','50.3','π × 4² = 50.265… mm², which rounds to 50.3 mm².',{type:'short',accepted:['50.3','50.3mm2','50.3mm²'],marks:2}],
 ['Ecology','decay-rate','An indicator changes in 25 seconds. Calculate the relative rate using 1/time, in s⁻¹.','0.04','1 ÷ 25 = 0.04 s⁻¹.',{type:'short',accepted:['0.04','0.04s-1','0.04s⁻¹'],marks:2}]
 ])addQ('Biology',b,b==='ocr'&&id==='osmosis-percent'?'Organisation':topic,'bio2-'+id,prompt,answer,explanation,{style:'Apply your understanding',...extra});
 // Reflect added sections in the displayed reading estimate.
 for(const t of PACKS.Biology[b].topics){const l=PACKS.Biology[b].overrides[t.id];l.minutes=Math.max(8,l.sections.length*2);}
}
