/* Build 6 Learning Lab: varied retrieval, application and exam practice. */
const COMMAND_WORDS={calculate:'Show the formula, substitute values, calculate and include the unit.',describe:'State what happens or what the data shows. Use values when given.',explain:'Give a reason and link cause to effect using science.',compare:'Give at least one similarity or linked difference using both items.',evaluate:'Use evidence for strengths and limitations, then reach a justified conclusion.',suggest:'Apply science to give a sensible answer supported by a reason.',state:'Give a short, precise fact. No explanation is normally needed.',give:'Provide the requested fact, example or reason.'};
const EQUATION_TRAINER=[
 ['Biology','Cell Biology','Magnification','magnification = image size ÷ real size','A cell image is 40 mm wide. The real cell is 0.04 mm wide.','1000'],
 ['Biology','Bioenergetics','Rate','rate = amount produced ÷ time','Pondweed produces 24 bubbles in 2 minutes. Find the rate.','12 bubbles/min'],
 ['Biology','Inheritance','Percentage','percentage = part ÷ total × 100','18 of 60 offspring show a feature. Find the percentage.','30%'],
 ['Biology','Organisation','Percentage change','change ÷ original × 100','Heart rate rises from 60 to 90 beats/min. Find the percentage increase.','50%'],
 ['Physics','Energy','Power','P = E ÷ t','A machine transfers 900 J in 30 s.','30 W'],
 ['Physics','Electricity','Resistance','R = V ÷ I','A component has 12 V across it and 2 A through it.','6 Ω'],
 ['Physics','Waves','Wave speed','v = f × λ','A 4 Hz wave has wavelength 3 m.','12 m/s'],
 ['Physics','Forces','Force','F = m × a','A 5 kg object accelerates at 3 m/s².','15 N'],
 ['Chemistry','Quantitative Chemistry','Moles','moles = mass ÷ Mr','Find moles in 20 g of a substance with Mr 40.','0.5 mol'],
 ['Chemistry','Rate & Extent of Chemical Change','Mean rate','rate = amount ÷ time','60 cm³ gas forms in 30 s.','2 cm³/s']
];
const SPOT_MISTAKES=[
 {s:'Chemistry',t:'Bonding',claim:'“Solid sodium chloride conducts because it contains charged ions.”',answer:'The ions are charged but fixed in the solid lattice. It conducts only when molten or dissolved because the ions can then move.'},
 {s:'Physics',t:'Forces',claim:'“An object moving at constant speed has no forces acting on it.”',answer:'Forces may act, but constant velocity means the resultant force is zero.'},
 {s:'Biology',t:'Bioenergetics',claim:'“Plants only respire at night.”',answer:'Plants respire continuously. They photosynthesise when light is available.'},
 {s:'Biology',t:'Cell Biology',claim:'“Diffusion needs energy from respiration.”',answer:'Diffusion is passive. Particles spread from a higher concentration to a lower concentration without energy from respiration.'},
 {s:'Biology',t:'Organisation',claim:'“Arteries always carry oxygenated blood.”',answer:'Arteries carry blood away from the heart. The pulmonary artery carries deoxygenated blood to the lungs.'},
 {s:'Biology',t:'Homeostasis & Response',claim:'“Insulin raises blood glucose.”',answer:'Insulin lowers blood glucose by helping cells take in glucose and causing the liver and muscles to store glucose as glycogen.'},
 {s:'Biology',t:'Inheritance',claim:'“A dominant allele is always the most common allele.”',answer:'Dominant describes which allele is expressed in a heterozygote. It does not mean the allele is common.'},
 {s:'Chemistry',t:'Energy Changes',claim:'“Breaking chemical bonds releases energy.”',answer:'Breaking bonds requires energy; making bonds releases energy.'}
];
const MATCH_SETS={
 equations:[['Power','energy ÷ time'],['Density','mass ÷ volume'],['Wave speed','frequency × wavelength'],['Moles','mass ÷ Mr']],
 units:[['Current','ampere'],['Potential difference','volt'],['Resistance','ohm'],['Activity','becquerel']],
 practicals:[['Independent variable','the factor deliberately changed'],['Dependent variable','the factor measured'],['Control variable','a factor kept constant'],['Repeat','helps identify variation and calculate a mean']]
};
const SUBJECT_MATCH_SETS={
 Biology:{cells:[['Nucleus','contains genetic material'],['Cell membrane','controls movement in and out'],['Mitochondria','site of aerobic respiration'],['Ribosome','makes proteins']],processes:[['Diffusion','particles move down a concentration gradient'],['Osmosis','water moves through a partially permeable membrane'],['Active transport','particles move against a concentration gradient'],['Respiration','releases energy from glucose']],practicals:MATCH_SETS.practicals},
 Chemistry:{particles:[['Atom','smallest part of an element'],['Ion','charged particle'],['Isotope','same protons but different neutrons'],['Molecule','two or more atoms bonded']],equations:[['Moles','mass ÷ Mr'],['Mean rate','amount ÷ time'],['Concentration','mass ÷ volume'],['Percentage yield','actual ÷ theoretical × 100']],practicals:MATCH_SETS.practicals},
 Physics:{equations:MATCH_SETS.equations,units:MATCH_SETS.units,practicals:MATCH_SETS.practicals}
};
const PRACTICAL_SIM=[
 {s:'Biology',title:'Microscopy',story:'Compare the size of onion cells using the same microscope.',iv:'part of the onion sampled',dv:'cell size measured with the eyepiece scale',control:'magnification and preparation method'},
 {s:'Biology',title:'Osmosis',story:'Investigate how sugar concentration changes the mass of potato cylinders.',iv:'sugar concentration',dv:'percentage change in potato mass',control:'time, temperature and cylinder size'},
 {s:'Biology',title:'Photosynthesis',story:'Investigate how lamp distance affects oxygen production by pondweed.',iv:'lamp distance',dv:'oxygen produced in a fixed time',control:'temperature and pondweed length'},
 {s:'Chemistry',title:'Reaction rate',story:'Investigate how acid concentration affects the time for magnesium to disappear.',iv:'acid concentration',dv:'time for magnesium to disappear',control:'temperature and magnesium size'},
 {s:'Physics',title:'Resistance',story:'Investigate how wire length affects electrical resistance.',iv:'wire length',dv:'resistance calculated from V ÷ I',control:'wire material, diameter and temperature'}
];
const LAB_DATA={
 Biology:{title:'Enzyme activity',aria:'A graph of enzyme activity rises to an optimum then falls sharply',path:'M45 195 C100 180 145 105 215 45 C250 70 265 155 300 188 S360 196 395 196',x:'Temperature (°C)',y:'Rate of reaction',question:'Why does the rate fall sharply above the optimum temperature?',options:[['denature','The enzyme’s active site changes shape'],['substrate','There is no substrate below the optimum'],['more','More enzyme-substrate complexes form']],answer:'denature',success:'Correct — high temperature changes the active site, so fewer substrates fit.'},
 Chemistry:{title:'Rate of reaction',aria:'A graph rises quickly then levels off',path:'M45 195 C95 80 150 45 235 38 S340 38 395 38',x:'Time (s)',y:'Gas volume (cm³)',question:'What does the flat section show?',options:[['done','The reaction has finished'],['faster','The reaction is getting faster'],['gaslost','All gas has escaped from the apparatus']],answer:'done',success:'Correct — no more product is forming, so the curve is flat.'},
 Physics:{title:'Current and potential difference',aria:'A straight line through the origin',path:'M45 195 L395 35',x:'Potential difference (V)',y:'Current (A)',question:'What does the straight line through the origin show?',options:[['constant','Resistance is constant'],['zero','Current is always zero'],['decrease','Resistance decreases continuously']],answer:'constant',success:'Correct — current is directly proportional to potential difference, so resistance is constant.'}
};
let labState={view:'menu',match:null,selected:null,equation:0,practical:0,examEnds:0};
function learningData(){state.learning ||= {xp:0,streak:0,lastStudy:'',confidence:[],modes:{},diagnostics:{}};return state.learning;}
function dayStamp(time=Date.now()){return new Date(time).toISOString().slice(0,10);}
function noteLearning(mode,points=5){const d=learningData(),today=dayStamp(),yesterday=dayStamp(Date.now()-86400000);if(d.lastStudy!==today){d.streak=d.lastStudy===yesterday?d.streak+1:1;d.lastStudy=today;}d.xp+=points;d.modes[mode]=(d.modes[mode]||0)+1;}
function learningSubject(){return SUBJECTS[state.learningSubject]?state.learningSubject:'Biology';}
function changeLearningSubject(subject){if(!SUBJECTS[subject])return;state.learningSubject=subject;labState={...labState,view:'menu',match:null,selected:null,equation:0,practical:0};save();learningLab(app());moveTop();}
function labSubjectSelector(compact=false){const subject=learningSubject(),count=questionPool(subject).length;return `<section class="card lab-subject-selector ${compact?'compact':''}"><div><div class="eyebrow">${compact?'LEARNING LAB SUBJECT':'CHOOSE YOUR LAB'}</div><b>${esc(subject)} Lab</b>${compact?'':`<small>${count} tailored practice questions · ${activeTopics(subject).length} topics</small>`}</div><label>Subject<select aria-label="Learning Lab subject" onchange="changeLearningSubject(this.value)">${Object.keys(SUBJECTS).map(s=>`<option value="${esc(s)}" ${s===subject?'selected':''}>${esc(s)}</option>`).join('')}</select></label></section>`;}
function dueQuestions(subject=learningSubject()){const now=Date.now();return questionPool(subject).filter(q=>{const x=questionRecord(q).srs?.[q.id];return x&&x.due<=now;});}
function setQuizConfidence(value){if(!session||session.answered)return;session.confidence=value;document.querySelectorAll('.confidence-button').forEach(x=>x.classList.toggle('selected',x.dataset.value===value));}
function learningAfterGrade(q,ok){const r=questionRecord(q);r.srs ||= {};const previous=r.srs[q.id]||{box:0};const confidence=session.confidence||'unsure';let box=ok?Math.min(5,previous.box+1):0;if(ok&&confidence==='guess')box=Math.min(box,1);const waits=[0,1,3,7,14,30];r.srs[q.id]={box,due:Date.now()+waits[box]*86400000,lastCorrect:ok};const d=learningData();d.confidence.push({at:Date.now(),correct:ok,confidence,subject:q.subject,topic:q.topic});d.confidence=d.confidence.slice(-200);noteLearning(session.mode||'quiz',ok?10:4);}
function quizLearningControls(q){const word=String(q.q).trim().split(/\s+/)[0].toLowerCase().replace(/[^a-z]/g,'');return `<div class="learning-controls"><div><small>How confident are you?</small><button class="confidence-button" data-value="guess" onclick="setQuizConfidence('guess')">Guessing</button><button class="confidence-button" data-value="unsure" onclick="setQuizConfidence('unsure')">Unsure</button><button class="confidence-button" data-value="sure" onclick="setQuizConfidence('sure')">Sure</button></div><div class="actions"><button class="text-button" onclick="revealQuizHint(1)">Hint ladder</button>${COMMAND_WORDS[word]?`<button class="text-button" onclick="showCommandTip('${word}')">What does “${esc(word)}” mean?</button>`:''}</div><div id="learning-help" aria-live="polite"></div></div>`;}
function maskHintAnswer(text,answer){let result=String(text||'');const value=String(answer||'').trim();if(value.length>1)result=result.replace(new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'ig'),'the key answer');return result;}
function questionHints(q){const question=String(q.q||''),explain=String(q.explain||''),section=q.section||q.topic;if(/new specimen|low power|objective lens|microscope/i.test(question))return ['Which objective gives the widest field of view?','Find and focus the specimen before increasing magnification.','Begin on low power, focus clearly, then move to higher power.'];if(/calculate|work out|how many|find/i.test(question)){const equation=(explain.match(/[^.]*=[^.]*?(?==|\.|$)/)||[])[0];return [`Choose the equation used in ${section}.`,equation?`Start with: ${maskHintAnswer(equation,q.answer)}`:`Write down the known values and their units before substituting.`,maskHintAnswer(explain,q.answer)];}const reason=maskHintAnswer(explain,q.answer),words=reason.split(/\s+/);const short=words.slice(0,Math.min(12,words.length)).join(' ');const optionHint=q.options?.length?`Rule out choices that do not fit ${section}. Look for the one supported by the scientific reason.`:`Recall the cause-and-effect link from ${section}.`;return [optionHint,short+(words.length>12?'…':''),reason];}
function revealQuizHint(level){const q=session?.queue[session.index],el=document.getElementById('learning-help');if(!q||!el)return;const hints=questionHints(q);el.innerHTML=`<div class="hint-card"><b>Hint ${level} of 3</b><p>${esc(hints[level-1])}</p>${level<3?`<button class="text-button" onclick="revealQuizHint(${level+1})">Stronger hint →</button>`:''}</div>`;}
function showCommandTip(word){const el=document.getElementById('learning-help');if(el)el.innerHTML=`<div class="hint-card"><b>${esc(word.toUpperCase())}</b><p>${esc(COMMAND_WORDS[word])}</p></div>`;}
function launchLabQuiz(mode){
 const subject=learningSubject();let pool=mode==='spaced'?dueQuestions(subject):questionPool(subject);const wanted=mode==='diagnostic'?5:mode==='spaced'?Math.min(12,pool.length):8;let selected=[];
 if(mode==='interleave'){const topics=[...new Set(pool.map(q=>q.topic))],groups=topics.map(t=>pool.filter(q=>q.topic===t).sort(()=>Math.random()-.5));for(let i=0;selected.length<wanted&&groups.some(g=>g.length);i++){const g=groups[i%groups.length];if(g.length)selected.push(g.shift());}}
 else selected=[...pool].sort(()=>Math.random()-.5).slice(0,wanted);
 session={queue:selected,index:0,score:0,answered:false,mode,requested:wanted};testSession=null;state.page='quiz';save();nav();renderQuiz();moveTop();
}
function labCard(title,text,action,iconText='→'){return `<button class="lab-card" onclick="${action}"><span>${iconText}</span><b>${esc(title)}</b><small>${esc(text)}</small></button>`;}
function subjectAttempts(subject){return Object.entries(state.records).reduce((n,[key,r])=>{try{return n+(JSON.parse(key)[0]===subject?(r.attempts||0):0);}catch{return n;}},0);}
function learningLab(a){
 const subject=learningSubject(),d=learningData(),due=dueQuestions(subject).length;
 if(labState.view!=='menu')return renderLabActivity(a);
 const attempts=subjectAttempts(subject);
 a.innerHTML=`${pageHeading(`${subject} Learning Lab.`,`Every activity is built around ${subject}. Change subject whenever you like.`)}${labSubjectSelector()}<div class="lab-summary"><div class="card"><small>Learning points</small><b>${d.xp}</b></div><div class="card"><small>Study streak</small><b>${d.streak} day${d.streak===1?'':'s'}</b></div><div class="card"><small>${subject} recall due</small><b>${due}</b></div><div class="card"><small>${subject} questions tried</small><b>${attempts}</b></div></div><div class="lab-section"><h3>Remember ${subject}</h3><div class="lab-grid">${labCard('Diagnostic check',`Five ${subject} questions reveal what to revise first.`,"launchLabQuiz('diagnostic')",'5')}${labCard('Spaced repetition',due?`${due} ${subject} questions are ready to revisit.`:`Your ${subject} recall queue will fill as you practise.`,"launchLabQuiz('spaced')",'↻')}${labCard('Active recall',`Answer a ${subject} question from memory before revealing the model.`,"openLab('recall')",'?')}${labCard('Sort and match',`Connect ${subject} terms, processes and meanings.`,"openLab('match')",'↔')}</div></div><div class="lab-section"><h3>Understand it</h3><div class="lab-grid">${labCard('Teach it back',`Explain your weakest ${subject} topic in simple words.`,"openLab('teach')",'✦')}${labCard('Spot the mistake',`Find and repair a ${subject} misconception.`,"openLab('mistake')",'!')}${labCard('Practical simulator',`Choose variables for a ${subject} investigation.`,"openLab('practical')",'⚗')}${labCard('Data and graphs',`Read ${subject} patterns and use evidence.`,"openLab('data')",'⌁')}</div></div><div class="lab-section"><h3>Apply it</h3><div class="lab-grid">${labCard('Equation trainer',`Practise calculations used in ${subject}.`,"openLab('equations')",'=')}${labCard('Exam walkthrough',`Build a ${subject} answer one step at a time.`,"openLab('walkthrough')",'✓')}${labCard(`Mixed ${subject} topics`,`Mix questions across ${subject} topics.`,"launchLabQuiz('interleave')",'⤨')}${labCard('Timed exam mode',`Complete a short ${subject} section against the clock.`,"openLab('timed')",'◷')}</div></div><div class="lab-section"><h3>Plan and celebrate</h3><div class="lab-grid">${labCard(`My ${subject} revision plan`,`See the best next steps from your ${subject} mastery.`,"openLab('plan')",'☷')}${labCard('Achievements','Celebrate effort, recall and improvement.',"openLab('achievements')",'★')}</div></div>`;
}
function openLab(view){labState={...labState,view,selected:null};learningLab(app());moveTop();}
function labBack(){labState.view='menu';learningLab(app());}
function renderLabActivity(a){
 const subject=learningSubject(),back='<button class="text-button" onclick="labBack()">← Learning Lab</button>'+labSubjectSelector(true),view=labState.view;
 if(view==='recall'){const pool=questionPool(subject),q=pool[Math.floor(Math.random()*Math.max(1,pool.length))];a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(subject.toUpperCase())} · ACTIVE RECALL</div><h2>${esc(q?.topic||'Start practising')}</h2><p class="question">${esc(q?.q||`Complete a ${subject} quiz first to build your recall bank.`)}</p>${q?`<details><summary>Reveal the model</summary><p>${esc(q.answer)}</p><p>${esc(q.explain)}</p></details><button class="btn primary" onclick="noteLearning('recall',8);openLab('recall')">Another ${esc(subject)} card</button>`:''}</section>`;return;}
 if(view==='match')return renderMatch(a,back);if(view==='teach')return renderTeach(a,back);if(view==='mistake')return renderMistake(a,back);if(view==='practical')return renderPractical(a,back);if(view==='data')return renderData(a,back);if(view==='equations')return renderEquation(a,back);if(view==='walkthrough')return renderWalkthrough(a,back);if(view==='timed')return renderTimed(a,back);if(view==='plan')return renderPlan(a,back);if(view==='achievements')return renderAchievements(a,back);
}
function currentMatchSets(){if(foundationPath(learningSubject())&&SUBJECT_MATCH_SETS[learningSubject()])return Object.fromEntries(Object.entries(SUBJECT_MATCH_SETS[learningSubject()]).map(([key,pairs])=>[key,pairs.filter(pair=>!['Moles','Percentage yield'].includes(pair[0]))]));return SUBJECT_MATCH_SETS[learningSubject()]||{topics:activeTopics(learningSubject()).slice(0,4).map(t=>[t.title,t.unit]),skills:[['Recall','retrieve without looking'],['Apply','use knowledge in a new situation'],['Analyse','find a pattern or relationship'],['Evaluate','judge evidence and reach a conclusion']]};}
function renderMatch(a,back){const sets=currentMatchSets(),kind=sets[labState.match]?labState.match:Object.keys(sets)[0],pairs=sets[kind];labState.match=kind;a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(learningSubject().toUpperCase())} · SORT AND MATCH</div><h2>Connect each pair</h2><div class="match-tabs">${Object.keys(sets).map(k=>`<button class="btn" onclick="labState.match='${k}';openLab('match')">${esc(k)}</button>`).join('')}</div>${pairs.map(([left,right],i)=>`<label>${esc(left)}<select id="match-${i}"><option value="">Choose…</option>${pairs.map(x=>`<option>${esc(x[1])}</option>`).join('')}</select></label>`).join('')}<button class="btn primary" onclick="checkMatch('${kind}')">Check matches</button><p id="lab-result" role="status"></p></section>`;}
function checkMatch(kind){const pairs=currentMatchSets()[kind],score=pairs.filter((x,i)=>document.getElementById('match-'+i).value===x[1]).length;document.getElementById('lab-result').textContent=`${score} of ${pairs.length} matched. ${score===pairs.length?'Excellent connections!':'Change the mismatched choices and try again.'}`;if(score===pairs.length){noteLearning('match',12);save();}}
function weakestLabTopic(){return activeRows().filter(x=>x.s===learningSubject()).sort((a,b)=>a.value-b.value)[0];}
function renderTeach(a,back){const x=weakestLabTopic(),l=x&&activeLesson(x.s,choice(x.s),x.t.id);a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(learningSubject().toUpperCase())} · TEACH IT BACK</div><h2>Explain ${esc(x?.t.title||`${learningSubject()} idea`)} simply</h2><p>Imagine you are teaching someone younger. Use plain words, then include the key subject terms.</p><textarea id="teach-answer" placeholder="My explanation…"></textarea><button class="btn primary" onclick="showTeachModel()">Compare with model</button><div id="lab-result"></div><template id="teach-model">${esc((l?.sections?.[0]?.body)||`Complete a ${learningSubject()} lesson to unlock a model.`)}</template></section>`;}
function showTeachModel(){const answer=document.getElementById('teach-answer').value.trim(),model=document.getElementById('teach-model').content.textContent;if(!answer)return document.getElementById('lab-result').textContent='Write your explanation first.';document.getElementById('lab-result').innerHTML=`<div class="hint-card"><b>Model explanation</b><p>${esc(model)}</p><p>Does yours name the idea and explain why it happens?</p></div>`;noteLearning('teach',10);save();}
function subjectMistakes(){const filtered=SPOT_MISTAKES.filter(x=>x.s===learningSubject()&&!(foundationPath(x.s)&&x.s==='Chemistry'&&x.t==='Energy Changes'));if(filtered.length)return filtered;return [{s:learningSubject(),t:'Exam skills',claim:'“A longer answer always earns more marks.”',answer:'Marks come from relevant, accurate points that answer the command word. Plan the needed points and support them with evidence or examples.'}];}
function renderMistake(a,back){const items=subjectMistakes(),item=items[Math.floor(Math.random()*items.length)];labState.selected=item;a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">SPOT THE MISTAKE</div><h2>${esc(item.s)} · ${esc(item.t)}</h2><blockquote>${esc(item.claim)}</blockquote><textarea id="mistake-answer" placeholder="The mistake is… A better answer is…"></textarea><button class="btn primary" onclick="showMistakeAnswer()">Reveal correction</button><div id="lab-result"></div></section>`;}
function showMistakeAnswer(){if(!document.getElementById('mistake-answer').value.trim())return document.getElementById('lab-result').textContent='Spot and correct the mistake first.';document.getElementById('lab-result').innerHTML=`<div class="hint-card"><b>Correction</b><p>${esc(labState.selected.answer)}</p></div>`;noteLearning('mistake',10);save();}
function subjectPracticals(){const filtered=PRACTICAL_SIM.filter(x=>x.s===learningSubject());return filtered.length?filtered:[{s:learningSubject(),title:`${learningSubject()} evidence check`,story:'Compare two methods fairly and decide which produces stronger evidence.',iv:'method used',dv:'result or score measured',control:'time allowed and starting conditions'}];}
function renderPractical(a,back){const pool=subjectPracticals(),p=pool[labState.practical%pool.length],options=[p.iv,p.dv,p.control,'the student’s prediction'];labState.selected=p;a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(learningSubject().toUpperCase())} · PRACTICAL SIMULATOR</div><h2>${esc(p.title)}</h2><p>${esc(p.story)}</p>${[['Independent variable','iv'],['Dependent variable','dv'],['Control variable','control']].map(([label,id])=>`<label>${label}<select id="prac-${id}"><option value="">Choose…</option>${[...options].sort().map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`).join('')}<button class="btn primary" onclick="checkPractical()">Check investigation</button><p id="lab-result"></p></section>`;}
function checkPractical(){const p=labState.selected,ok=['iv','dv','control'].every(k=>document.getElementById('prac-'+k).value===p[k]);document.getElementById('lab-result').textContent=ok?'Correct — the investigation can test the intended relationship.':'Check what is changed, what is measured and what must stay the same.';if(ok){noteLearning('practical',15);labState.practical++;save();}}
function subjectGraph(){return LAB_DATA[learningSubject()]||{title:`${learningSubject()} results`,aria:'A line graph rises from left to right',path:'M45 195 C140 165 245 95 395 35',x:'Independent variable',y:'Result',question:'What pattern does the graph show?',options:[['rise','The result increases as the independent variable increases'],['fall','The result decreases'],['none','There is no pattern']],answer:'rise',success:'Correct — both variables increase across the graph.'};}
function renderData(a,back){const d=subjectGraph();a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(learningSubject().toUpperCase())} · DATA AND GRAPHS</div><h2>${esc(d.title)}</h2><svg class="lab-chart" viewBox="0 0 420 240" role="img" aria-label="${esc(d.aria)}"><path d="M45 15V205H405"/><path class="chart-line" d="${d.path}"/><text x="175" y="232">${esc(d.x)}</text><text transform="translate(15 165) rotate(-90)">${esc(d.y)}</text></svg><label>${esc(d.question)}<select id="data-answer"><option value="">Choose…</option>${d.options.map(([value,label])=>`<option value="${value}">${esc(label)}</option>`).join('')}</select></label><button class="btn primary" onclick="checkData()">Check conclusion</button><p id="lab-result"></p></section>`;}
function checkData(){const d=subjectGraph(),ok=document.getElementById('data-answer').value===d.answer;document.getElementById('lab-result').textContent=ok?d.success:'Look at the axes, describe the pattern, then explain it using the subject idea.';if(ok){noteLearning('data',12);save();}}
function subjectEquations(){return EQUATION_TRAINER.filter(e=>e[0]===learningSubject()&&!(foundationPath(e[0])&&e[2]==='Moles'));}
function renderEquation(a,back){const pool=subjectEquations();if(!pool.length){const q=questionPool(learningSubject()).find(x=>/calculate|work out|find/i.test(x.q));a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(learningSubject().toUpperCase())} · NUMBER SKILLS</div><h2>Use evidence precisely</h2><p class="question">${esc(q?.q||`Practise selecting and using numerical evidence in ${learningSubject()}.`)}</p>${q?`<details><summary>Reveal worked answer</summary><p>${esc(q.answer)}</p><p>${esc(q.explain)}</p></details>`:''}</section>`;return;}const e=pool[labState.equation%pool.length];labState.selected=e;a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(learningSubject().toUpperCase())} · EQUATION TRAINER</div><h2>${esc(e[2])}</h2><div class="equation-strip">${esc(e[3])}</div><p class="question">${esc(e[4])}</p><input id="equation-answer" aria-label="Answer"><button class="btn primary" onclick="checkEquation()">Check answer</button><p id="lab-result"></p></section>`;}
function checkEquation(){const expected=labState.selected[5],value=document.getElementById('equation-answer').value.toLowerCase().replace(/\s/g,''),ok=value===expected.toLowerCase().replace(/\s/g,'')||value===expected.split(' ')[0].toLowerCase();document.getElementById('lab-result').textContent=ok?`Correct: ${expected}.`:'Try again. Choose the equation, substitute carefully and include the unit.';if(ok){noteLearning('equations',12);labState.equation++;save();}}
function renderWalkthrough(a,back){const pool=questionPool(learningSubject()),q=pool.find(x=>x.type==='writing')||pool[0],word=String(q?.q||'explain').split(/\s+/)[0].toLowerCase().replace(/[^a-z]/g,'');a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(learningSubject().toUpperCase())} · EXAM WALKTHROUGH</div><h2>Build the answer one step at a time</h2><p class="question">${esc(q?.q||`Explain a ${learningSubject()} idea.`)}</p><ol class="walkthrough"><li><b>Decode:</b> ${esc(COMMAND_WORDS[word]||'Identify exactly what the question is asking.')}</li><li><b>Recall:</b> Write the key fact, method or process.</li><li><b>Apply:</b> Link it to the details in this question.</li><li><b>Check:</b> Include evidence, linked reasoning and enough points for the marks.</li></ol><details><summary>Reveal model answer</summary><p>${esc(q?.answer||'')}</p><p>${esc(q?.explain||'')}</p></details><button class="btn primary" onclick="noteLearning('walkthrough',10);openLab('walkthrough')">Try another ${esc(learningSubject())} walkthrough</button></section>`;}
function renderTimed(a,back){a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">TIMED EXAM MODE</div><h2>Eight-question ${esc(learningSubject())} sprint</h2><p>You will have twelve minutes. Hints remain available, but use them only if you are stuck.</p><button class="btn primary" onclick="startTimedExam()">Start 12-minute section</button></section>`;}
function startTimedExam(){labState.examEnds=Date.now()+12*60000;launchLabQuiz('timed');}
function timedBanner(){if(session?.mode!=='timed')return '';const mins=Math.max(0,Math.ceil((labState.examEnds-Date.now())/60000));return `<div class="timed-banner">⏱ About ${mins} minute${mins===1?'':'s'} remaining</div>`;}
function renderPlan(a,back){const subject=learningSubject(),rows=activeRows().filter(x=>x.s===subject).sort((x,y)=>x.value-y.value).slice(0,6);a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">${esc(subject.toUpperCase())} · PERSONAL REVISION PLAN</div><h2>Your next ${rows.length} ${esc(subject)} steps</h2><p>Start with weaker topics, then return to due recall questions.</p>${rows.map((x,i)=>`<div class="plan-row"><span>${i+1}</span><div><b>${esc(x.t.title)}</b><small>${x.value}% mastery · ${status(x.value)}</small></div><button class="btn" onclick="openLesson(${arg(x.s)},${arg(x.t.id)})">Learn</button></div>`).join('')}${dueQuestions(subject).length?`<button class="btn primary" onclick="launchLabQuiz('spaced')">Review ${dueQuestions(subject).length} due questions</button>`:''}</section>`;}
function renderAchievements(a,back){const d=learningData(),attempts=subjectAttempts(learningSubject()),modes=Object.keys(d.modes).length,awards=[['First step',attempts>=1,`Answer one ${learningSubject()} question`],['Building momentum',attempts>=25,`Try 25 ${learningSubject()} questions`],['Recall regular',(d.modes.spaced||0)>=3,'Complete three spaced-recall sessions'],['Learning explorer',modes>=5,'Use five different learning modes'],['On a roll',d.streak>=3,'Study on three consecutive days'],['Century',d.xp>=100,'Earn 100 learning points']];a.innerHTML=back+`<section class="card lab-activity"><div class="eyebrow">ACHIEVEMENTS</div><h2>${esc(learningSubject())} progress worth celebrating</h2><div class="achievement-grid">${awards.map(([name,earned,how])=>`<div class="achievement ${earned?'earned':''}"><span>${earned?'★':'☆'}</span><b>${esc(name)}</b><small>${esc(how)}</small></div>`).join('')}</div></section>`;}
