/* Original AQA 8464 shared-tier benchmark. No network or mastery writes. */
const OSMOSIS_KEY='gcseStudyHub-staging-706L-osmosis-v1';
const OSMOSIS_STAGES=['Start with what you know','Explore the membrane','Work with mass','Explain and repair','Apply independently','Remember'];
const OSMOSIS_CHECKS=[
 {q:'Which particle moves by osmosis?',options:['Water','Sugar'],correct:0,reason:'Water is the solvent; sugar is a dissolved solute. Osmosis describes water movement.',retry:'A membrane lets water through but blocks starch. Which crosses by osmosis?',again:['Water molecules','Starch molecules']},
 {q:'At equal concentrations, what happens to water?',options:['It stops','It moves both ways equally overall'],correct:1,reason:'Particles keep moving randomly. Equal opposing flows mean no NET movement, not no movement.',retry:'Two solutions have equal water concentration. Why does mass stay constant?',again:['All particles stop','Water enters and leaves at equal rates']},
 {q:'A plant cell in dilute solution takes in water. What prevents bursting?',options:['Its wall resists expansion','Its wall prevents all water entry'],correct:0,reason:'Water crosses the cell membrane. The strong cell wall resists expansion; the cell becomes turgid. Animal cells lack this wall and may burst.',retry:'A root cell becomes firm after watering. Why?',again:['Water enters; the wall resists expansion','The wall blocks water']},
 {q:'For percentage mass change, divide the change by…',options:['Final mass','Initial mass'],correct:1,reason:'Compare the change with the starting amount: (final − initial) ÷ initial × 100. A loss gives a negative result.',retry:'A 5 g sample falls to 4 g. Which denominator belongs in the calculation?',again:['4 g','5 g']}
];
const OSMOSIS_RUBRIC=['Water leaves the plant cells overall (accept net outward movement).','Outside is more concentrated / has lower water concentration than inside.','Water crosses a partially permeable cell membrane by osmosis.','Mass falls: (3.4 − 4.0) ÷ 4.0 × 100 = −15%.','Keep time, temperature, tissue source and cylinder dimensions constant; accept two suitable controls.','Blot surface solution before weighing and repeat each concentration, calculating a mean.'];
let ot={stage:0,answers:{},repairs:{},results:{},mode:'immediate'},otNotice='',otStorageNotice='';
function otLoad(){try{const v=JSON.parse(localStorage.getItem(OSMOSIS_KEY)||'null');if(v&&Number.isInteger(v.stage)&&v.stage>=0&&v.stage<6&&v.answers&&v.repairs&&v.results){ot=v;ot.resumeStage=Number.isInteger(v.resumeStage)&&v.resumeStage>=0&&v.resumeStage<6?v.resumeStage:v.stage;}}catch{otStorageNotice='Saved tutor data could not be read. Existing Study Hub progress is unaffected.';}}
function otSave(){try{localStorage.setItem(OSMOSIS_KEY,JSON.stringify(ot));otStorageNotice='';}catch{otStorageNotice='Tutor progress cannot be saved in this browser. Keep this page open and copy your results.';}const status=document.getElementById('ot-storage-status');if(status)status.textContent=otStorageNotice;}
function otDue(now=Date.now()){return Boolean(ot.completedAt&&now>=ot.completedAt+7*86400000);}
function otVideo(){return `<div class="ot-video"><h4>Watch: how water moves</h4><p>A narrated animation that explains what you are seeing in plain English. Turn your sound on. Subtitles appear in their own panel below the animation. Pause at the prediction and explain your answer.</p><video controls playsinline preload="none" poster="media/osmosis-poster.png" aria-label="Narrated beginner osmosis explainer"><source src="media/osmosis-explainer-clear-subtitles.mp4" type="video/mp4">Your browser cannot play this video. Read the description below.</video><p><a href="media/osmosis-narrated-transcript.txt" target="_blank" rel="noopener">Read the full spoken explanation</a></p><details><summary>Read the video description</summary><p>Blue spheres represent water; gold spheres represent sugar. A membrane divides a dilute solution from a concentrated solution. Water crosses both ways, with greater net flow towards the concentrated side. Sugar remains on its side in this model. At equal concentrations, water still crosses both ways equally overall. In dilute surroundings, plant cells take in water and become turgid as their walls resist expansion; animal cells may swell and burst. In concentrated surroundings, water leaves cells overall and they shrink. This is a qualitative illustration; particle sizes and rates are not to scale.</p></details></div>`;}
function osmosisEntry(s,c,t){if(s!=='Biology'||c.board!=='aqa'||t!=='Cell Biology'||state.scienceCourse!=='trilogy')return '';otLoad();return `<section class="card ot-entry"><div class="eyebrow">INTERACTIVE TUTOR · 20–25 MINUTES</div><h3>Why does a potato gain or lose water?</h3>${otVideo()}<p>Explore a membrane, make predictions and explain your thinking. AQA osmosis · Foundation and Higher.</p><button class="btn primary" onclick="otStart(false)">${ot.completedAt?'Review your osmosis journey':ot.stage?'Continue osmosis journey':'Start osmosis journey'} →</button>${otDue()?'<button class="btn" onclick="otStart(true)">Day-7 independent check is due</button>':''}</section>`;}
function otStart(delayed){otLoad();if(delayed){ot.mode='delayed';ot.stage=4;}else{ot.mode='immediate';ot.stage=ot.completedAt?5:(ot.resumeStage??ot.stage);}otRender();}
function otEscape(v){return String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));}
function otField(id,label){return `<label for="${id}">${label}</label><textarea id="${id}" rows="3" ${["fade","calc","mass-transfer"].includes(id)?`aria-describedby="${id}-feedback" aria-invalid="${Boolean(ot.mass?.[id]?.invalid)}"`:""} oninput="otStore(this.id)" onchange="otStore(this.id)">${otEscape(ot.answers[id]||'')}</textarea>`;}
function otStore(id){const value=document.getElementById(id).value;if(ot.mass?.[id]&&ot.answers[id]!==value)ot.mass[id].correct=false;ot.answers[id]=value;otSave();}
function otNext(){for(const el of document.querySelectorAll('.ot textarea'))otStore(el.id);if(ot.stage===0&&!document.getElementById('pre').value.trim()){otNotice='Try your starting explanation before continuing.';otRender();return;}if(ot.stage===2&&!otMassReady()){otNotice='Check both mass calculations and complete any fresh transfer calculation without hints before continuing.';otRender();return;}if((ot.stage===1&&!ot.answers.prediction?.trim())||(ot.stage===2&&(!ot.answers.fade?.trim()||!ot.answers.calc?.trim()))){otNotice='Try the prediction or calculations before continuing.';otRender();return;}if(ot.stage===3&&!OSMOSIS_CHECKS.every((q,i)=>ot.repairs[i]?.correct)){otNotice='Complete all four prediction-and-reason checks, including any changed cases, before continuing.';otRender();return;}otNotice='';for(const el of document.querySelectorAll('.ot textarea'))otStore(el.id);ot.stage=Math.min(5,ot.stage+1);if(ot.mode!=='delayed')ot.resumeStage=Math.max(ot.resumeStage||0,ot.stage);otSave();otRender();}
function otBack(){ot.stage=Math.max(0,ot.stage-1);otSave();otRender();}
function otRender(){const n=ot.stage;app().innerHTML=`<section class="card ot"><button class="text-button" onclick="openLesson('Biology','Cell Biology')">← Cell Biology</button><p class="eyebrow">OSMOSIS LAB · ${ot.mode==='delayed'?'DAY-7 CHECK':'FOUNDATION & HIGHER'}</p><progress max="6" value="${n+1}" aria-label="Journey stage"></progress><p>Stage ${n+1} of 6 · ${OSMOSIS_STAGES[n]}</p><h2 tabindex="-1" id="ot-title">${OSMOSIS_STAGES[n]}</h2><p role="status">${otEscape(otNotice)}</p><p id="ot-storage-status" role="status">${otEscape(otStorageNotice)}${typeof location!=='undefined'&&location.protocol==='file:'?' Local-file saving is not reliable across browsers. Use the same hosted site address in a normal browser window for reliable resuming.':''}</p>${otBody(n)}<div class="actions">${n>0&&ot.mode!=='delayed'?'<button class="btn" onclick="otBack()">Previous stage</button>':''}${n<5&&n!==4?'<button class="btn primary" onclick="otNext()">Save & continue →</button>':''}</div></section>`;document.getElementById('ot-title')?.focus?.();}
function otBody(n){if(n===0)return `<p>Take about 2 minutes. Try these before teaching begins. It is fine to be unsure.</p>${otField('pre','In your own words: what is a dilute solution, what can a partially permeable membrane let through, and do particles stop moving at equilibrium?')}<p>Your starting explanation is saved for comparison, not automatically graded.</p>`;
if(n===1)return `${otVideo()}<p><b>Solvent:</b> water. <b>Solute:</b> a dissolved substance such as sugar. A dilute solution has less dissolved sugar per volume than a concentrated one. A partially permeable membrane lets some particles through.</p><p>Our model lets water through and blocks sugar. Water moves randomly in both directions. <b>Net movement</b> means the difference between the two flows.</p><label for="ot-concentration">Sugar concentration on the right (left stays at 2 model units)</label><input id="ot-concentration" type="range" min="0" max="4" value="4" oninput="otModel(this.value)"><div id="ot-model"></div><button class="btn" onclick="otModel(document.getElementById('ot-concentration').value)">Show / update water movement</button>${otField('prediction','Before showing the model: predict net movement when the right is more concentrated. Explain why.')}<p>Move the slider to explore dilute, equal and concentrated solutions. This is a simplified concentration model, not a measured rate or a cell under pressure. Plant walls also create pressure as cells become turgid.</p><div class="worked">Osmosis: net water movement from a dilute to a more concentrated solution through a partially permeable membrane. No energy from respiration is required.</div>`;
if(n===2)return `<p>Allow about 5 minutes. First follow the worked example: a potato gains water in a more dilute solution because water enters cells through their membranes.</p><ol><li>Initial mass 4.0 g; final mass 4.6 g.</li><li>Change = 4.6 − 4.0 = +0.6 g.</li><li>Percentage change = 0.6 ÷ 4.0 × 100 = <b>+15%</b>.</li></ol><p>Now fade the support: 8.0 g → 7.2 g. Change = −0.8 g. Complete −0.8 ÷ ___ × 100.</p>${otField('fade','Write the denominator and signed percentage.')}<button class="btn" onclick="otCalc('fade',-10)">Check worked practice</button>${otMassFeedback("fade")}<p>Independent practice: a fresh sample changes from 6.0 g to 6.9 g.</p>${otField('calc','Give its signed percentage change, including %.')}<button class="btn" onclick="otCalc('calc',15)">Check independent practice</button>${otMassFeedback("calc")}<div id="ot-mass-transfer">${otTransferBody()}</div><h3>Read the practical evidence</h3>${typeof transportGraph==='function'?transportGraph():''}${otField('graph','Estimate where the graph crosses zero. What does this tell you about water movement?')}<button class="btn" onclick="otGraph()">Check graph reasoning</button><div id="ot-graph-feedback" role="status"></div>`;
if(n===3)return `<p>Allow 4 minutes. Choose a prediction <b>and write your reason</b>. Each mistake opens a different recheck.</p>${OSMOSIS_CHECKS.map((q,i)=>`<fieldset><legend>${i+1}. ${q.q}</legend>${q.options.map((a,j)=>`<label><input type="radio" name="mc${i}" value="${j}" ${ot.choices?.['mc'+i]===String(j)?'checked':''} onchange="otChoice(this)"> ${a}</label>`).join('')}${otField('reason'+i,'Explain your choice') }<button class="btn" onclick="otCheck(${i},false)">Check reasoning practice</button><div id="repair${i}" role="status">${otRepairBody(i)}</div></fieldset>`).join('')}`;
if(n===4)return otAssessment();
const r=ot.results;return `<p><b>Journey completed</b> means you attempted the learning stages, not that understanding is proven.</p><p>Immediate structured check: ${r.immediate?r.immediate.score+'/10; transfer '+r.immediate.transfer+'/4':'not yet submitted'}. Day-7 structured check: ${r.delayed?r.delayed.score+'/10; transfer '+r.delayed.transfer+'/4':'pending'}.</p><p>Written explanations and the six-mark answer still need review against the rubric. Aim for immediate ≥8/10 and ≥3/4 transfer; day 7 ≥7/10 and ≥3/4 transfer. Confirm equilibrium reasoning in your writing.</p><p>Return on ${ot.completedAt?new Date(ot.completedAt+7*86400000).toLocaleDateString('en-GB'):'completion + 7 days'} for changed contexts and numbers. The reminder appears here on this device when you revisit; it cannot notify you while the app is closed.</p><button class="btn" onclick="otReview()">View saved answers and marking guidance</button><div id="ot-review"></div>${otDue()?'<button class="btn primary" onclick="otStart(true)">Take day-7 check</button>':''}<p>Progress uses a separate local key. Keep the same browser and site address; clearing browser data removes it. Existing Study Hub backups do not include this tutor record.</p>`;}
function otModel(v){v=Number(v);const direction=v===2?'No net movement; water continues both ways.':v>2?'Net water movement: left → right.':'Net water movement: right → left.';document.getElementById('ot-model').innerHTML=`<div class="ot-membrane" role="img" aria-label="Left sugar concentration 2; right ${v}. Water crosses both ways. ${direction}"><div>LEFT<br>Sugar: 2<br>Water molecules ● ● ●</div><div class="ot-bar">Partially<br>permeable<br>membrane<br><span class="ot-flow">→<br>←</span></div><div>RIGHT<br>Sugar: ${v}<br>Water molecules ● ● ●</div></div><p role="status"><b>${direction}</b> Sugar stays on its side. ${v===2?'Equal opposing flows.':v>2?'More water crosses rightward than leftward overall.':'More water crosses leftward than rightward overall.'}</p>`;}
// Calculation evidence stays inside the existing tutor record; bank mastery is never written.
function otMassRecord(id){ot.mass ||= {};return ot.mass[id] ||= {wrong:0,assisted:false,revealed:false,correct:false,message:''};}
function otMassQuestion(id){if(id==='fade')return {initial:8,final:7.2};if(id==='calc')return {initial:6,final:6.9};return ot.massTransfer;}
function otMassFeedback(id){const r=ot.mass?.[id];return `<div class="worked" id="${id}-feedback" role="status" aria-live="polite" aria-atomic="true" tabindex="-1">${otEscape(r?.message||'')}</div>`;}
function otTransferBody(){const q=ot.massTransfer;if(!q)return '';return `<h3>Fresh transfer calculation</h3><p>Try a new calculation when you are ready.</p><p>This sample changes from ${q.initial.toFixed(1)} g to ${q.final.toFixed(1)} g. Calculate its signed percentage change without hints. Round to two decimal places if needed. A supported answer is practice evidence only.</p>${otField('mass-transfer','Signed percentage change, including %') }<button class="btn" onclick="otCalc('mass-transfer')">Check fresh transfer</button>${otMassFeedback('mass-transfer')}<button class="btn" onclick="otNewTransfer()">I'm ready to try again!</button>`;}
function otNewTransfer(){ot.transferHistory ||= [];if(ot.massTransfer)ot.transferHistory.push({question:ot.massTransfer,evidence:ot.mass?.['mass-transfer'],answer:ot.answers['mass-transfer']});const index=ot.transferHistory.length;const initial=10+index;ot.massTransfer={initial,final:initial+(index%2?3:-2)};ot.mass ||= {};delete ot.mass['mass-transfer'];ot.answers['mass-transfer']='';otSave();const host=document.getElementById('ot-mass-transfer');if(host)host.innerHTML=otTransferBody();}
function otMassReady(){return Boolean(ot.mass?.fade?.correct&&ot.mass?.calc?.correct&&(!(ot.mass.fade.assisted||ot.mass.calc.assisted)|| (ot.mass?.['mass-transfer']?.correct&&!ot.mass['mass-transfer'].assisted)));}
function otCalc(id){const q=otMassQuestion(id);if(!q)return;otStore(id);
 const r=Object.assign(otMassRecord(id),lessonPercentageFeedback(q,ot.answers[id],id==='fade',otMassRecord(id)));
 const field=document.getElementById(id),feedback=document.getElementById(id+'-feedback');
 field.setAttribute?.('aria-describedby',id+'-feedback');
 field.setAttribute?.('aria-invalid',String(r.invalid));
 feedback.textContent=r.message;feedback.focus?.();otSave();
 if(r.assisted&&(r.correct||r.revealed)&&id!=='mass-transfer'&&!ot.massTransfer)otNewTransfer();
 if(id==='mass-transfer'&&r.correct&&r.assisted){otNewTransfer();}
}
function otCheck(i,retry){const q=OSMOSIS_CHECKS[i],el=document.querySelector(`input[name="${retry?'retry':'mc'}${i}"]:checked`);otStore('reason'+i);if(!el||!ot.answers['reason'+i].trim()){document.getElementById('repair'+i).textContent='Choose an answer and explain your reason first.';return;}const ok=Number(el.value)===q.correct;ot.repairs[i]={correct:ok,rechecked:retry,reason:ot.answers['reason'+i]};otSave();document.getElementById('repair'+i).innerHTML=otRepairBody(i);}
function otItems(delayed){return [
 {q:delayed?'A sealed model sac contains dilute solution; the outside is more concentrated. The membrane passes water only. Predict the change.':'An unfamiliar model capsule contains concentrated solution in a dilute bath. Its membrane passes water only. Predict the change.',o:['Net water enters; mass rises','Net water leaves; mass falls','Sugar enters by osmosis'],a:delayed?1:0,w:2},
 {q:delayed?'An animal cell is placed in concentrated solution. Predict and explain its size change.':'An animal cell is placed in dilute solution. Predict and explain its size change.',o:['Water enters; it swells and may burst because it has no wall','Water leaves; it shrinks','The wall stops water entry'],a:delayed?1:0,w:2},
 {q:'Equal water concentrations on both sides of a membrane: what happens?',o:['Water stops moving','Water moves both ways equally overall','Water moves only one way'],a:1,w:1},
 {q:'Which defines osmosis?',o:['Sugar crossing a cell wall','Net water movement through a partially permeable membrane from dilute to concentrated solution','Any particle movement using energy'],a:1,w:1},
 {q:'Which procedure improves mass measurements?',o:['Weigh dripping tissue','Blot consistently before weighing; repeat and calculate a mean','Change the immersion time for each sample'],a:1,w:1},
 {q:delayed?'Results at 0, 0.3, 0.6 mol/dm³ are +12%, 0%, −12%. Estimate zero net mass change concentration.':'Results at 0, 0.2, 0.4 mol/dm³ are +10%, 0%, −10%. Estimate zero net mass change concentration.',o:['0 mol/dm³',delayed?'0.3 mol/dm³':'0.2 mol/dm³',delayed?'0.6 mol/dm³':'0.4 mol/dm³'],a:1,w:1}
];}
function otAssessment(){const delayed=ot.mode==='delayed',prefix=ot.mode;return `<p>Allow about 6 minutes. Work without hints or outside help. These original items are separate from the question bank. Each transfer item is worth 2 points; the whole structured check totals 10.</p><form id="ot-assessment" onsubmit="otSubmit(event)">${otItems(delayed).map((q,i)=>`<fieldset><legend>${i<2?'Unfamiliar transfer · ':''}${q.q} (${q.w} points)</legend>${q.o.map((a,j)=>`<label><input type="radio" name="exit${i}" value="${j}" ${ot.choices?.[prefix+'exit'+i]===String(j)?'checked':''} onchange="otChoice({name:ot.mode+this.name,value:this.value})" required> ${a}</label>`).join('')}</fieldset>`).join('')}${otField(prefix+'-transfer','Explain both unfamiliar predictions in your own words, including the membrane and concentration difference. Explain why water still moves at equilibrium.')}<p>${delayed?'A sample changes from 7.5 g to 6.0 g.':'A sample changes from 5.0 g to 5.5 g.'} Calculate signed percentage mass change (2 points).</p><label for="exit-number">Signed percentage, with %</label><input id="exit-number" value="${otEscape(ot.answers[prefix+'-number']||'')}" oninput="ot.answers[ot.mode+'-number']=this.value;otSave()" required placeholder="e.g. −12%"><p><b>Original GCSE-style question · 6 marks · separate rubric review</b><br>A plant cylinder changes from 4.0 g to 3.4 g in concentrated sucrose. Explain the mass change and calculate its percentage. Describe controls and measurement steps for a reliable comparison across concentrations.</p>${otField(prefix+'-exam','Write your six-mark answer before revealing guidance.')}<label><input type="checkbox" id="ot-help" ${ot.help?.[prefix]?'checked':''} onchange="ot.help ||= {};ot.help[ot.mode]=this.checked;otSave()"> I used outside help (record this alongside results)</label><button class="btn primary" type="submit">Submit & reveal marking guidance</button><p id="ot-submit-message" role="status"></p></form>`;}
function otMark(choices,value,delayed){let score=0,transfer=0;otItems(delayed).forEach((q,i)=>{if(Number(choices[i])===q.a){score+=q.w;if(i<2)transfer+=q.w;}});if(/^[+−-]?\d+(?:\.\d+)?\s*%$/.test(value.trim())&&Number(value.replace('%','').replace('−','-'))===(delayed?-20:10))score+=2;return {score,transfer};}
function otSubmit(e){e.preventDefault();const choices=otItems(ot.mode==='delayed').map((_,i)=>document.querySelector(`input[name="exit${i}"]:checked`)?.value);for(const el of document.querySelectorAll('.ot textarea'))otStore(el.id);if(choices.some(v=>v===undefined)||!ot.answers[ot.mode+'-transfer']?.trim()||!ot.answers[ot.mode+'-exam']?.trim()){document.getElementById('ot-submit-message').textContent='Attempt every item and both written explanations before revealing guidance.';return;}const value=document.getElementById('exit-number').value;ot.history ||= [];if(ot.results[ot.mode])ot.history.push({mode:ot.mode,...ot.results[ot.mode]});ot.results[ot.mode]={...otMark(choices,value,ot.mode==='delayed'),choices,value,help:document.getElementById('ot-help').checked,at:Date.now()};if(!ot.completedAt)ot.completedAt=Date.now();ot.stage=5;if(ot.mode==='immediate')ot.resumeStage=5;otSave();otRender();otReview();}
function otReview(){document.getElementById('ot-review').innerHTML=`<h3>Your evidence and marking guide</h3><p>${ot.history?.length?'This check has been repeated; earlier results remain in the local tutor record. Repeated attempts are practice, not unseen evidence.':''}</p><p>Structured results are automatically checked, but recognising options is weaker evidence than independently explaining them. No automatic free-text grading or mastery claim is made.</p>${Object.entries(ot.results).map(([mode,r])=>`<h4>${mode==='delayed'?'Day 7':'Immediate'} · ${r.score}/10 · transfer ${r.transfer}/4 · ${r.help?'outside help recorded':'no outside help recorded'}</h4><ol>${otItems(mode==='delayed').map(q=>`<li>${otEscape(q.q)}<br><b>${otEscape(q.o[q.a])}</b></li>`).join('')}</ol><p>Calculation: ${mode==='delayed'?'(6.0 − 7.5) ÷ 7.5 × 100 = −20%':'(5.5 − 5.0) ÷ 5.0 × 100 = +10%'}.</p>`).join('')}<details><summary>Saved written attempts (copy these for a teacher)</summary>${Object.entries(ot.answers).map(([id,v])=>`<h4>${otEscape(id)}</h4><p class="ot-written">${otEscape(v)}</p>`).join('')}</details><p>For each 2-point transfer explanation: 1 for the correct net direction/effect and 1 for the correct concentration/membrane or cell-wall reasoning. At equilibrium, require continued bidirectional movement with equal opposing rates. Review the starting explanation separately; it has no numerical pretest score.</p><p>Six-mark checklist: one mark per point below. Accept equivalent scientific wording; do not credit sugar moving by osmosis, a wall described as the partially permeable membrane, “particles stop”, division by final mass or a positive mass-loss result. This analytic practice rubric is not an official AQA levels mark scheme.</p><ol>${OSMOSIS_RUBRIC.map(v=>`<li>${v}</li>`).join('')}</ol><p>Day-7 transfer and numbers change. The six-mark question repeats for comparison and is not unseen retention evidence. A teacher should review writing before judging the benchmark successful.</p>`;}

function otGraph(){otStore("graph");document.getElementById("ot-graph-feedback").textContent=ot.answers.graph.trim()?"About 5 g sugar per 100 mL final solution, interpolated between 4 and 6. No net mass change: water still crosses both ways at equal rates overall. Test more concentrations near the crossing to improve the estimate.":"Try an estimate and explanation before checking.";}

function otChoice(el){ot.choices ||= {};ot.choices[el.name]=el.value;otSave();}

function otRepairBody(i){const q=OSMOSIS_CHECKS[i],r=ot.repairs[i];if(!r)return '';const ok=r.correct;return `<p>${ok?'Prediction correct. Compare your explanation:':'Let’s repair this idea:'} ${q.reason}</p><p>Your writing is saved for rubric review; a correct choice alone does not establish understanding.</p>${!ok?`<fieldset><legend>${q.retry}</legend>${q.again.map((a,j)=>`<label><input type="radio" name="retry${i}" value="${j}"> ${a}</label>`).join('')}<p>Update your reason above, then try this changed case.</p><button class="btn" onclick="otCheck(${i},true)">Check changed case</button></fieldset>`:''}`;}
